### ISSUE TITLE
Example for Raven.setUserContext()

### ISSUE THREAD

**Issue by Flur3x** [nuxt-community/sentry-module#10]
Hi, thanks for this nice module. I'd like to ask if you could give an example on how/where to call 

`   
    this.$raven.setUserContext(
		{
			email: 'foo@example.com'
	    }
    );
`

It probably should be called as soon as possible, but there is no such thing as nuxtClientInit right now and I can't access the app context  in nuxtServerInit. I don't even know if it's necessary to call it on the server side already. Sure, I could add it to a middleware, but then it would be called/evaluated with every route change ...

Help is much appreciated! :)

Best,
Daniel

**Comment by DiederikvandenB** [comment]
Could you maybe share some code of where you check if a user is authenticated? We have an OAuth2 package which takes care of all authentication. What I'd suggest is to import and call Raven there as soon as you know the user's email address.

Let me know if I can help any further.

**Comment by Flur3x** [comment]
Hey, sorry for the late answer. After I wrote this issue, I realized that I can just import:

```js
import raven from raven-js
```

into my own wrapper library (for reports) instead of using this.$raven directly. And I also realized that it is absolutely possible to access the app context in nuxtServerInit() nowadays. ;)

But anyway, I'm very unclear about the vue/nuxt context and how I work with it safely. Let's say I call this.$raven.setUserContext() in nustServerInit(). Can I be sure, that it sets the context for the right user when concurrent requests come in?

In sentry-client.js you have these two lines:

```js
  ctx.$raven = Raven
  inject('raven', Raven)
```

What is the first line for? Isn't inject('raven', Raven) enough? I'm just interested, as I couldn't find that out with the nuxt documentation, and I've also seen that other nuxt modules do both. I'm asking because, as I said, I import `raven-js` into my own wrapper lib and then I just export the functions and inject them via:

```js
export default (ctx, inject) => {
	inject('sentry', sentry);
};
```

My first thought: Maybe I have to inject a factory function instead of my library directly for security reasons (concurrent requests), but you actually also just inject raven without that. So it seems to be fine.

Hope it's not too much to read! I would really like to support the nuxt ecosystem, but first there's so much to learn. :D

**Comment by DiederikvandenB** [comment]
Alright, so the last time I actually used Nuxt was right about when I created this repo, and therefore I must admit that I cannot guarantee that my answers will be correct.

> Can I be sure, that it sets the context for the right user when concurrent requests come in?
As far as I know, the context is created as a result from a request. Therefore, they have a one to one relationship.

> What is the first line for?
I am not completely sure, as I did not author that code, but I'd guess they do the same and the former is the fallback / older syntax for the latter. In that case it make sense you couldn't find it in the docs because you're only looking at the most recent docs obviously.

So I think you should be fine doing it the way you are.
