### ISSUE TITLE
Doesn't take router base into account when uploading releases

### ISSUE THREAD

**Issue by rchl** [nuxt-community/sentry-module#105]
### Version

[v3.0.0](https://github.com/sentry-module/releases/tag/v3.0.0)

### Reproduction link

[http://nuxt.js](http://nuxt.js)

### Steps to reproduce

`router.base` that is by default set to `/` and can be overridden, isn't taken into account in:

https://github.com/nuxt-community/sentry-module/blob/9092e9da2fecbb9e1dd5e6aad8194040062641e5/lib/module.js#L48

### What is expected ?

`webpackConfig.urlPrefix` matches `~path.join(router.base, build.publicPath)`.

### What is actually happening?

If base is overridden to, let's say `/foo/` then client resources will be served from `/foo/_nuxt/` but uploaded release artifacts on Sentry will have prefix `~/_nuxt/` so won't be matched against actual files.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sentry-module/issues/c71">#c71</a>)</em></sub></div>

**Comment by aldarund** [comment]
PR welcome :)
