### ISSUE TITLE
Support "false" string in process.env.SENTRY_DISABLE_CLIENT_SIDE

### ISSUE THREAD

**Issue by pSchaub** [nuxt-community/sentry-module#13]
If you do this in the env file ...
```
SENTRY_DISABLE_CLIENT_SIDE=false
```
... the script will still think that the sentry client should be disabled. The reason is that "false" is a string and not a boolean.

So please add a check if the string "false" or "0" is set to support the above environment variable as a normal user would expect it.

**Comment by DiederikvandenB** [comment]
Sorry for the late response. Will be fixed in the next release.
