### ISSUE TITLE
Add $sentry to context

### ISSUE THREAD

**Issue by Thooto** [nuxt-community/sentry-module#130]
### What problem does this feature solve?

Other nuxt plugins are accessible in the nuxt context with a `$`. This modules isn't.

### What does the proposed changes look like?

The nuxt context object would have a `$sentry` attribute.

Would need to add in _lib/module/sentry.(client|server).js_:
```js
inject('sentry', Sentry)
ctx.$sentry = Sentry // Currently missing
```

In some plugin:
```js
export function (ctx) {
  ctx.$sentry // Now accessible
}
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sentry-module/issues/c80">#c80</a>)</em></sub></div>

**Comment by papertokyo** [comment]
Came here to say this. Please merge #131

**Comment by rchl** [comment]
I'm not sure why you would need that? It's accessible at `app.$sentry`. I'd say other modules are wrong in extending context given that `inject` doesn't inject directly to `context` but to `context.app`.

**Comment by gangsthub** [comment]
Yes, @rchl, it is accesible through `app.$sentry`. But it could be used in some other places like `store` and tests.

**Comment by rchl** [comment]
Inject function also exposes on store.
And other plugins can access it from `app.$sentry` as well.

**Comment by Atinux** [comment]
#131 is merged and available in `v3.1.0`

**Comment by rchl** [comment]
@Atinux interesting to see that you agree with those changes. Do you see this as a convenient alias or there is some other reason?

I wonder if original issue/patch authors just thought that this allows something that wasn't possible before, which is not the case?

**Comment by Atinux** [comment]
Actually I plan to change the Nuxt behaviour to make the `inject()` add it to `context` directly, most of Nuxt modules actually do this (axios, auth, http, etc)

**Comment by Thooto** [comment]
Hi, thanks for merging the PR !

@rchl 
> I wonder if original issue/patch authors just thought that this allows something that wasn't possible before, which is not the case?

I knew it was possible to access it from `context.app`, however in the plugins for my Nuxt app, I usually destructure the context so the syntax:
`const somePlugin: Plugin = ({ $sentry }) => { ... }`

is a bit more concise than:
`const somePlugin: Plugin = ({ app: { $sentry } }) => { ... }`

But I guess it is more a matter of harmonization ; seeing that other plugins were doing that. But you have a good point saying
> I'd say other modules are wrong in extending context given that inject doesn't inject directly to context but to context.app.

Anyway this was a tiny PR :)
