### ISSUE TITLE
Do not initialize this module if no Sentry information is passed (like in a local environment)

### ISSUE THREAD

**Issue by tolgap** [nuxt-community/sentry-module#14]
If you leave any Sentry information out of your .env file, this module still tries to send a HTTP request to sentry.io but (of course) with a wrong URL: `POST https://sentry.io/api//store/?sentry_version=7&sentry_client=raven-js%2F3.23.1&sentry_key=null 400 (BAD REQUEST)`.

It would be nice if this module would check if all required Sentry info was empty, the plugin simply does not initialize. Otherwise I have to resort to polluting my `nuxt.config.js` with a bunch of `process.env` checks 😄 .

**Comment by DiederikvandenB** [comment]
Sorry for the late response. Will be fixed in the next release.
