### ISSUE TITLE
Specifying string in webpackConfig.inclide results in an error.

### ISSUE THREAD

**Issue by kimulaco** [nuxt-community/sentry-module#148]
### Version

[3.2.2](https://github.com/sentry-module/releases/tag/3.2.2)

### Reproduction link

[https://codesandbox.io/s/nuxt-sentry-module-r7wtc?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/nuxt-sentry-module-r7wtc?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

1. Install `@nuxtjs/sentry` and add the following config to nuxt.config.js.
```
export default {
  ...
  modules: ['@nuxtjs/sentry'],
  sentry: {
    dsn: process.env.SENTRY_DSN || '',
    disableServerSide: true,
    disableServerRelease: true,
    config: {
      environment: 'dev'
    },
    webpackConfig: {
      include: '.',
      release: 'v1.0.0'
    },
  }
  ...
}
```
2. Run `nuxt generate` or `nuxt build`.
3. I get the following error in terminal.
```
 ✖ Nuxt Fatal Error
TypeError: options.webpackConfig.include.push is not a function     
```

### What is expected ?

As with `@ sentry/webpack-plugin`, it is desirable that a string is allowed.
https://github.com/getsentry/sentry-webpack-plugin/blob/master/README.md#options

### What is actually happening?

`webpackConfig.include` only allows arrays.

https://github.com/nuxt-community/sentry-module/blob/master/lib/module.js#L61-L66

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sentry-module/issues/c83">#c83</a>)</em></sub></div>

**Comment by rchl** [comment]
Would you expect that the sentry module's code still adds its own path when user has specified something?

**Comment by kimulaco** [comment]
I don't yet have a deep understanding of the sentry module, but I think you should add your own path if needed for tracking.
I think it is best to convert to the array when you specify string in webpackConfig.inclide.

I'm sorry if I was saying something wrong.

**Comment by rchl** [comment]
It makes sense to combine user's and module's paths I think.
