### ISSUE TITLE
Inject keys on runtime

### ISSUE THREAD

**Issue by dorianamouroux** [nuxt-community/sentry-module#16]
I'm using this package https://github.com/samtgarson/nuxt-env to inject my environment variable on runtime; and avoid having keys on the buildtime. Would `sentry-module` play nicely with it; to avoid the issues mentioned in the README of `nuxt-env` ?

**Comment by DiederikvandenB** [comment]
Disclaimer: I have not used that package myself before, but I can't think of anything that would cause problems. Have you tried it yourself?

Furthermore, it is essential you understand the warning in their readme. For instance, if you would add your AWS credentials to that package, everyone would be able to connect to your AWS account by simply finding the credentials in your source code. Make sure all your sensitive environment variables can only be accessed server side.
