### ISSUE TITLE
exception.values.0.stacktrace.frames: Missing value for required attribute

### ISSUE THREAD

**Issue by bjesus** [nuxt-community/sentry-module#163]
### Version

[v3.2.4](https://github.com/sentry-module/releases/tag/v3.2.4)

### Reproduction link

[https://sweeps.ai](https://sweeps.ai)

### Steps to reproduce

install the Sentry module
have some issues
look at the Sentry dashboard

### What is expected ?

to be able to see details about the issues

### What is actually happening?

very little information displayed, an error saying: `There was 1 error encountered while processing this event: exception.values.0.stacktrace.frames: Missing value for required attribute` appears.

### Additional comments?

My config looks like this:
`sentry: {
    dsn: "https://xxx@sentry.io/xxx",
    initialize: process.env.NODE_ENV === "production",
    publishRelease: true,
    webpackConfig: {
      setCommits: {
        repo: "sweeps/website",
        auto: true
      }
    },
    config: {} // Additional config
  },`

I also get tons of errors because everytime a user with ublock origin goes on the website some requests are blocked and that generates a "Failed to fetch" error on Sentry, but i'm not sure if that's a general sentry issue or sentry-module one.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sentry-module/issues/c87">#c87</a>)</em></sub></div>

**Comment by rchl** [comment]
There is nothing to go with here without more information but likely the issue is not in this module.

You would maybe be better asking that question at https://github.com/getsentry/sentry-javascript where someone from Sentry could look at your event.

**Comment by bjesus** [comment]
Okay, before I go and ask at `sentry-javascript` - is there _any_ information I can give that would help here? am I the only one seeing this issue?

**Comment by destemidosistemas** [comment]
I saw the same problem. But in my case, related to Oracle connection fail, where if the connection fail, I was capturing in the "catch", like this:
`Sentry.captureException(error);`
Now, I'm capturing like this and it works fine:
`Sentry.captureException(error.message || error);`.
I think that, depending on the properties of the error object, Sentry does not handle it correctly.

**Comment by rchl** [comment]
I don't think we can do anything here.

**Comment by zeusstl** [comment]
Receiving the same error in the Sentry Issues interface starting recently and cannot understand why. We have Sentry across a large codebase and not sure how to debug this. Error messages that have been in place for years are suddenly having this message.

Effectively this doesn't break the app, but it creates an unknown error that the team does not understand.

Can anyone from the Sentry team explain what the error means? It is missing a required attribute, but what attribute or what type of attribute? We have all the same error handlers, error consoles, etc as before this started.

Any more detailed explanation about this error would be extremely helpful.

**Comment by zeusstl** [comment]
Sorry. Upon rereading the prior comments it is clear that I've commented in the wrong place. I've created a ticket in the sentry-react-native repo:
https://github.com/getsentry/sentry-react-native/issues/2429
