### ISSUE TITLE
Publish 3.3.0 to npm

### ISSUE THREAD

**Issue by matthieusieben** [nuxt-community/sentry-module#165]
### Version

[v3.3.0](https://github.com/sentry-module/releases/tag/v3.3.0)

### Reproduction link

[https://www.npmjs.com/package/@nuxtjs/sentry](https://www.npmjs.com/package/@nuxtjs/sentry)

### Steps to reproduce

```
npm install @nuxtjs/sentry
``` 

### What is expected ?

Version 3.3.0 to be installed

### What is actually happening?

Version 3.2.4 installed

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sentry-module/issues/c89">#c89</a>)</em></sub></div>

**Comment by rchl** [comment]
Ops, I thought it was published... Now merged latest Sentry dependencies and released 3.3.1.
