### ISSUE TITLE
must have a SENTRY_PRIVATE_KEY env, even though SENTRY_DSN exists

### ISSUE THREAD

**Issue by boltonomous** [nuxt-community/sentry-module#17]
This module works well, but one issue I ran into is that I had to have SENTRY_PRIVATE_KEY defined for this to work... even though SENTRY_DSN was defined.

It looks like the culprit is here:
https://github.com/nuxt-community/sentry-module/blob/master/lib/sentry.js#L22

I'm happy to fix, just wanted to make sure there wasn't more to this before doing so.  Thanks!

**Comment by DiederikvandenB** [comment]
I'm sorry! I think that line should be replaced by:

`if (!options.DSN && !options.public_key && !options.private_key) {`

I will have time to fix this tonight, but in case you need the fix earlier you can always submit a PR. Thanks for reporting!
