### ISSUE TITLE
How to programatically check if Sentry is disabled?

### ISSUE THREAD

**Issue by mystrdat** [nuxt-community/sentry-module#176]
Before, I used to rely on `this.$sentry` being undefined, but a recent update seems to have broken that and I'm getting a warning with `$sentry.captureException() called, but sentry plugin is disabled.` How can I check if Sentry is disabled and suppress the warning?

**Comment by rchl** [comment]
`disabled` option should disable it completely. `initialize` option keeps the object but not initialized.

**Comment by mystrdat** [comment]
I am using the `disabled` option as `disabled: process.env.NODE_ENV === 'development'` and yet `this.$sentry` logs as the following object:
![chrome_Yrlv61wiuq](https://user-images.githubusercontent.com/1652895/80396424-e5da4800-88b4-11ea-9b6e-a149101e2eec.png)

**Comment by rchl** [comment]
Right, forgot about it, we mock $sentry now when it's disabled.
This is so that the code doesn't break when you disable Sentry during development (as null checking everywhere would be annoying).

If the warnings annoy you, maybe we can introduce setting to disable warnings (or just not warn at all).

**Comment by mystrdat** [comment]
```
i Sentry client side errors will not be logged because the disable option has been set
i Sentry server side errors will not be logged because the disable option has been set
```

I suppose since Sentry is reporting itself as disabled during stack startup and clearly states the above, reporting it again for all calls of the plugin is sort of duplicit. I see why you're mocking the object, but then I wouldn't expect any additional warnings.
