### ISSUE TITLE
Allow overriding webpack plugin urlPrefix

### ISSUE THREAD

**Issue by sajadhsm** [nuxt-community/sentry-module#177]
### What problem does this feature solve?

If `build.publicPath` is pointing to a CDN, then the `urlPrefix` is not correct. Being able to override it, is necessary in this situation.

### What does the proposed changes look like?

Maybe a quick fix would be:
```javascript
if (!options.webpackConfig.urlPrefix) {
    const publicPath = posix.join(this.options.router.base, this.options.build.publicPath)
    options.webpackConfig.urlPrefix = publicPath.startsWith('/') ? `~${publicPath}` : publicPath
}
```
or setting the `urlPrefix` before merging the options.

I can submit a PR if the solution is OK.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sentry-module/issues/c95">#c95</a>)</em></sub></div>

**Comment by rchl** [comment]
Yes, looks like an OK solution.
