### ISSUE TITLE
Report on server side does not work

### ISSUE THREAD

**Issue by timur-sh** [nuxt-community/sentry-module#185]
Hi.

I am trying to send report to a sentry:
`context.$sentry.captureMessage("Just simple message");`

On a cliend side it is working. But, on server side is not. I am trying to do it at `nuxtServerInit`

Configuration:
```
sentry: {
  dsn: 'MY_DSN',
  config: {
  },
}
```

**Comment by rchl** [comment]
Try with https://docs.sentry.io/error-reporting/configuration/?platform=browser#debug
Should tell you why it's ignoring the event then.

**Comment by timur-sh** [comment]
Thank you for reply!

I enabled the debug options and found the problem.
