### ISSUE TITLE
I get undefined on my server log when accessing $raven from app context

### ISSUE THREAD

**Issue by pauldariye** [nuxt-community/sentry-module#19]
<img width="303" alt="screen shot 2018-03-22 at 02 38 54" src="https://user-images.githubusercontent.com/3650761/37755037-34386dee-2d7a-11e8-86d0-938d5e828701.png">

**Comment by DiederikvandenB** [comment]
This is probably because you're trying to access $raven from the `asyncData` function, is that correct?

The following code works perfectly:

``` js
fetch({ $raven }) {
  console.log($raven);
}
```

This loads `raven-js`. If you want serverside reporting, just `import Raven from 'raven';`

**Comment by DiederikvandenB** [comment]
I would if you can convince me why importing Raven as usual is not sufficient :). As far as I am aware (have not been using Nuxt/this module for a while now, just maintaining it), this approach will not result in your environment loading a new instance of Raven, and therefore I don't think it's necessary to inject it in to an SSR context.

Of course I can be wrong, and in that case I'm more than happy to help you out here!

**Comment by pauldariye** [comment]
I get your point and I think I may have been calling it in the wrong place.

**Comment by developius** [comment]
Does anyone have an example of using sentry to handle errors returned from `asyncData`?

Example page:

```js
export default {
  asyncData({ params, $api }) {
    // 404 thrown by backend service (uses axios underneath)
    return $api.getSomething(params.id).then(something => {
      // make `something` available to the page
      return { something }
    })
  }
}
```

```js
// plugins/api.js
import Vue from 'vue'
import ApiService from '@/services/ApiService'

export default (ctx, inject) => {
  const api = new ApiService({ $axios: ctx.app.$axios })
  ctx.$api = api
  inject('api', api)
}
```

```js
// services/ApiService.js
export default class ApiService {
  constructor(ctx) {
    this.$axios = ctx.$axios
  }

  getSomething(id){
    return this.$axios.get('/api/something/' + id)
  }
}
```

If a 404 is thrown by the API, I'd like nuxt to handle the error normally (which it does - it shows the `NuxtServerError` page) and an error to be logged in Sentry (not working 😢). Any ideas?

**Comment by pauldariye** [comment]
@developius, you can wrap your api calls in a `try/catch` block or use `.catch` like so:

```javascript

export default {
  asyncData({ params, $api, app: { $raven } }) {
    // 404 thrown by backend service (uses axios underneath)
    return $api.getSomething(params.id).then(something => {
      // make `something` available to the page
      return { something }
    }).catch(err => {
       console.log(err)
       $raven.captureException(err)
    })
  }
}

```

**Comment by SAGV** [comment]
@pauldariye but how would you access $raven from `nuxtServerInit`? Unfortunately, app.$raven is undefined there…

In the same time, if I add `@nuxtjs/axios`, it is visible in `nuxtServerInit` as app.$axios. But I cannot spot the difference in module initialisation between these two modules…

**Comment by SAGV** [comment]
@pauldariye sorry for the late answer. On one side, it does help. On the other, it requires a custom error page (while I'm happy with the default one) and it doesn't cover cases where I'd like to send a error/message to Sentry but still continue executing the code (aka send error to Sentry if error is in try-catch block)

**Comment by SAGV** [comment]
But anyway, if someone wants to use the method proposed by @pauldariye and the default error page, you'd need to copy-paste the default error page [from here](https://github.com/nuxt/nuxt.js/blob/dev/packages/app/template/components/nuxt-error.vue) (might require you to remove/alter some templating)

And then you can pass error to sentry like:
```
mounted() {
    this.$raven.captureException(new Error(this.error.message))
  }
```
If you just pass the error object (which is not the actual JS error), you risk getting `Non-Error exception captured with keys: message, statusCode` error by Sentry.
