### ISSUE TITLE
Which type of sentry integration is used for nuxt?

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [nuxt-community/sentry-module#193]
Im curious to know what platform should I choose at sentry to integrate with nuxt? I mean, I can select browser javascript, vue, node, express, is there the correct one? Can I add one for the node and one for the browser part? how does that works in the end?

**Comment by rchl** [comment]
I'd select `Vue` but I'm not sure if it has any relevance in Sentry UI apart from cosmetics (icon).

Technically Nuxt would be a `Node.js` project on the server-side and `Vue` on the browser side but since you have to pick one, `Vue` is probably more accurate.
