### ISSUE TITLE
Plugin not using runtime variables from $config

### ISSUE THREAD

**Issue by marosmola** [nuxt-community/sentry-module#202]
### What problem does this feature solve?

When using application in more than one environment, different configuration settings for sentry module are needed during runtime. 

### What does the proposed changes look like?

Override default configuration to use runtime config which would have higher priority than using environment variables.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sentry-module/issues/c105">#c105</a>)</em></sub></div>

**Comment by serkansural** [comment]
For anyone whose build environment is different from where their app run, this is the workaround for applying runtime **DSN**

```
publicRuntimeConfig: {
    ...
    sentry: {
      config: {
        dsn: process.env.SENTRY_DSN,
        environment: process.env.SENTRY_ENVIRONMENT,
      },
    },
  },
  sentry: {
    dsn: true,
    ...
   }
    ```
