### ISSUE TITLE
Ability to disable for specific environments?

### ISSUE THREAD

**Issue by acidjazz** [nuxt-community/sentry-module#21]
I'd like to not load this for my local env, is there any way i can dynamically load the module and/or specify a config option that disables it and then decide based on an ENV variable?

**Comment by DiederikvandenB** [comment]
There are multiple ways to achieve this. In our opinion, the easiest way to do this is to use `.env` files. Quick example:

`.env.local`
```
SENTRY_DSN=
```

`.env.production`
```
SENTRY_DSN=your sentry dsn
```

Just make sure that your production environment uses the correct env file and you're set.

**Comment by acidjazz** [comment]
@DiederikvandenB great idea! thanks!
