### ISSUE TITLE
Error: Template src not found: C:\...\node_modules\@nuxtjs\sentry\lib\sentry.client.js

### ISSUE THREAD

**Issue by nelsonlarocca** [nuxt-community/sentry-module#221]
Hi 
After updating to ver 4.3.3 I'm getting this:

✖ Nuxt Fatal Error
                                         │
   │
                                         │
   │   Error: Template src not found:

   C:\<project path>\node_modules\@nuxtjs\sentry\lib\sentry.client.js  

UPDATING: I installed previous versions 4.3.x and still didn't work, nevertheless checked out another project using 4.0.3 and works fine and the lib is found in the repository.

Missing file starting version 4.2.0
https://github.com/nuxt-community/sentry-module/tree/v4.2.0/lib

**Comment by rchl** [comment]
See https://github.com/nuxt-community/sentry-module/issues/206
