### ISSUE TITLE
How to set Private Key

### ISSUE THREAD

**Issue by PhouvanhKCSV** [nuxt-community/sentry-module#23]
Hi,

in my nuxt.config.js i have
```
...
sentry: {
    public_dsn: 'xxx',
    project_id: 'xxx',
  }
...
```

but when i run build, i got the message "nuxt:sentry disabled because no (private) key was found

Where can i get the private key? (and public key). i have read their docs only see document about "dsn"

Thanks

**Comment by DiederikvandenB** [comment]
Please go over the readme again. You either provide an entire DSN, or you enter a `public_dsn`, a `public_key` **and a** `private_key`.
