### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by IlyaSemenov** [nuxt-community/sentry-module#246]
### Reproduction Link

here:

https://github.com/nuxt-community/sentry-module/blob/fe1c8d53f9c0b4c9f526cc3e260cbfc5a8134a60/README.md#L44

the link goes to https://docs.sentry.io/error-reporting/configuration/?platform=browser

which redirects to https://docs.sentry.io/platforms/browser showing 404 Not Found.

### What is Expected?

Non-broken link.

### What is actually happening?

Broken link.

### Why is that important

The documentation never mentions if Sentry DSN in nuxt config should be public or private. I tried to follow the link to see the options, but it didn't work.

* On the one hand, public makes more sense because part of sentry integration runs on the client.
* On the other hand, using private DSN during SSR makes sense, too, and public could be derived by simply stripping the password part. Not sure if this module does that or not.

**Comment by rchl** [comment]
> * and public could be derived by simply stripping the password part. Not sure if this module does that or not.

I guess by "password" you mean the "secret" (https://docs.sentry.io/product/sentry-basics/dsn-explainer/).

The module doesn't strip the secret. It expects you not to provide the secret in the first place as Sentry UI/documentation should generally provide you DSN without the secret.

What would be the point of using a DSN with a secret on the server-side?

BTW. I never thought of using separate DSN for the server and browser parts and it's not supported currently.

**Comment by IlyaSemenov** [comment]
No offense intended - it's just that my Sentry provides two DSNs:

<img width="930" alt="Screenshot 2020-10-29 at 16 13 47" src="https://user-images.githubusercontent.com/128121/97548600-e7baca80-1a01-11eb-8c6f-009f4d7937ec.png">

so I was confused which of the two I should put into config. I believe I'm not the only person who could be confused.

**Comment by rchl** [comment]
Interesting. My project doesn't show the DSN with the secret at all:

![Screenshot 2020-10-29 at 10 23 24](https://user-images.githubusercontent.com/153197/97549738-0e144200-19d1-11eb-9c2a-2e82076dddbb.png)

(It's a `Vue` type project but I see the same with `express` type also)

**Comment by IlyaSemenov** [comment]
I am using a relatively old self-hosted Sentry 8.13.0, they've probably changed it in newer versions.

**Comment by IlyaSemenov** [comment]
I've updated my Sentry to v10 and I see that non-public DSNs are obsolete. But that wasn't really my question, I just wanted to point that the link to the documentation needs to be updated.

**Comment by rchl** [comment]
Can you find an appropriate page to replace the old one with?
(just trying to delegate a bit since I don't have plenty of time currently ;))
