### ISSUE TITLE
Change default integration settings?

### ISSUE THREAD

**Issue by RyanMulready** [nuxt-community/sentry-module#251]
I've run into this issue when using Vue and the Bootstrap-vue auto scroll plugin. https://github.com/getsentry/sentry-javascript/issues/2957

Their temporary solution seems to work when not using this module but when using it I can not seem to modify the `tryCatch` settings. I would have assumed the following would work but it does not.

```javascript
    clientIntegrations: {
        TryCatch: { eventTarget: false },
    },
```

**Comment by rchl** [comment]
This is the correct way to do it.

The only reason I could think of why this might not be working is due to the order that the integrations are registered. Doing it this way would end up with `TryCatch` integration being registered last. Maybe it needs to be registered before `Vue`?

**Comment by RyanMulready** [comment]
I looked deeper into it and I think the issue lies here; https://github.com/nuxt-community/sentry-module/blob/6a6a3be408fbf559ecdcda9db659fcae3c9fdce9/lib/plugin.client.js#L4 `tryCatch` is not exported from the import.  https://github.com/getsentry/sentry-javascript/blob/master/packages/integrations/src/index.ts but instead here https://github.com/getsentry/sentry-javascript/blob/1dda72490572b45ec17ba27aaac835dc8c08140d/packages/browser/src/integrations/index.ts which causes a fatal error

**Comment by rchl** [comment]
Thanks for investigating it. I've prepared a fix in #257. Haven't actually checked this use case but it should work.

**Comment by rmarmitt** [comment]
Looks like this still not working. Any suggestions would be appreciated

**Comment by rchl** [comment]
What is not working? Are the options not being passed to Sentry? If so then report a proper bug with reproduction.

If the options are passed but you are not getting the behavior that you would expect then I would suggest asking/reporting in the Sentry project.

**Comment by rmarmitt** [comment]
Actually, I tried to disable `eventTarget ` but seems not working. I saw this issue in #https://github.com/getsentry/sentry-javascript/issues/2957 and tried to apply these settings, but without success. Needs further investigation

**Comment by RyanMulready** [comment]
> Actually, I tried to disable `eventTarget ` but seems not working. I saw this issue in #[getsentry/sentry-javascript#2957](https://github.com/getsentry/sentry-javascript/issues/2957) and tried to apply these settings, but without success. Needs further investigation

@rmarmitt I can confirm at least for https://github.com/getsentry/sentry-javascript/issues/2957 this does in fact work. If it isn't for you, it's likely a different issue.

```js
sentry: {
    clientIntegrations: {
        // https://github.com/getsentry/sentry-javascript/issues/2957
        TryCatch: { eventTarget: false },
    },
}
```

**Comment by rmarmitt** [comment]
> > Actually, I tried to disable `eventTarget ` but seems not working. I saw this issue in #[getsentry/sentry-javascript#2957](https://github.com/getsentry/sentry-javascript/issues/2957) and tried to apply these settings, but without success. Needs further investigation
> 
> @rmarmitt I can confirm at least for [getsentry/sentry-javascript#2957](https://github.com/getsentry/sentry-javascript/issues/2957) this does in fact work. If it isn't for you, it's likely a different issue.
> 
> ```js
> sentry: {
>     clientIntegrations: {
>         // https://github.com/getsentry/sentry-javascript/issues/2957
>         TryCatch: { eventTarget: false },
>     },
> }
> ```

@RyanMulready well, yours application is hanging due a "navigation guard" error in Vue-Router?  Have this solution worked for you? 

When I have added a .`catch()` to a `$router.replace` (actually in this point our app crashes), no matters if `eventTarget` is flagged or not, the Sentry stops from freezing page. But that's just one point, there may be others in our code that throws an "navigation guard" error and maybe freeze entire application.

Thanks for your time
