### ISSUE TITLE
How does nuxt integrate sentry, whether it can give a case similar to next.js？

### ISSUE THREAD

**Issue by 1391020381** [nuxt-community/sentry-module#270]
How does nuxt integrate sentry, whether it can give a case similar to next.js？
I can't handle Sentry-source-map well
https://github.com/vercel/next.js/blob/canary/examples/with-sentry/README.md

**Comment by rchl** [comment]
I don't know what is your problem. You need to explain what exactly is not working well. If it's difficult for you to explain with words then create a repo that shows the problem.
