### ISSUE TITLE
How can I add pluggable integrations not listed in SENTRY_BROWSER_INTEGRATIONS to sentry module?

### ISSUE THREAD

**Issue by JkmAS** [nuxt-community/sentry-module#274]
I would like to add e.g. CaptureConsole integration. But if I do it in the nuxt.config.js, I'll get 

`Sentry integration "CaptureConsole" is not recognized and will be ignored. nuxt:sentry`

because the integrations is missing in array [SENTRY_BROWSER_INTEGRATIONS](https://github.com/nuxt-community/sentry-module/blob/master/lib/core/hooks.js#L10).

This is my part of nuxt config:

```
  sentry: {
    dsn: ``,
    config: {
      maxBreadcrumbs: 100,
      // ...
    },
    clientIntegrations: {
      CaptureConsole: {
        levels: ['error'],
      },
    },
  },
```

Maybe it'll help, if you add information about these integrations to doc https://sentry.nuxtjs.org/sentry/options#clientintegrations.

- Caused by: https://github.com/nuxt-community/sentry-module/pull/257
- Related issue: https://github.com/nuxt-community/sentry-module/issues/191?

Thx

**Comment by rchl** [comment]
Addressing in #275
