### ISSUE TITLE
Throwing inside an async asyncData hook causes headers to be sent twice

### ISSUE THREAD

**Issue by Radiergummi** [nuxt-community/sentry-module#278]
### Version
@nuxtjs/sentry: `5.0.2`
nuxt: `2.15.1`

### Sentry configuration
Default config

### Reproduction Link
Cannot really reproduce yet

### Steps to reproduce
1. Create a page component with an async `asyncData` hook that throws an error
   ```ts
   import Vue from 'vue';
    
   export default Vue.extend( {
     async asyncData(): Promise<void> {
       throw new Error('test');
     }
   }
   ```
2. Load the page

### What is Expected?
The error is caught, Nuxt's error handler catches it and displays the Youch error page in development or the `error.html` template in production.

### What is actually happening?
A response seems to be sent prematurely, as indicated by the following error reported on the console:
```
 ERROR  Error: test                                                                                                                                      16:27:30
    at asyncData (src/views/Home.vue:75:0)
    at promisify (dist/utils.js:292:0)
    at server.js:1749:82
    at Array.map (<anonymous>)
    at module.exports../dist/server.js.__webpack_exports__.default (dist/server.js:269:0)


 ERROR  Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client                                                              16:27:30
    at new NodeError (node:internal/errors:329:5)
    at ServerResponse.setHeader (node:_http_outgoing:573:11)
    at sendResponse (/node_modules/@nuxt/server/dist/server.js:312:9)
    at errorMiddleware (/node_modules/@nuxt/server/dist/server.js:371:3)
```

Therefore, the default node HTTP handler error output is sent to the browser (I cannot determine which is the first response generated, presumably the one by Node itself):
```http
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Content-Length: 523
Content-Security-Policy: default-src 'none'
Content-Type: text/html; charset=utf-8
Date: Tue, 23 Feb 2021 12:44:54 GMT
Keep-Alive: timeout=5
X-Content-Type-Options: nosniff

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: test<br>
    at asyncData (src/views/Home.vue:75:0)<br>
    at promisify (dist/utils.js:292:0)<br>
    at server.js:1749:82<br>
    at Array.map (<anonymous>)<br>
    at module.exports../dist/server.js.__webpack_exports__.default (dist/server.js:269:0)</pre>
</body>
</html>
```

Could this be related to #245? I noticed the error only appears if the sentry module is enabled in the nuxt configuration.

**Comment by Radiergummi** [comment]
@rchl this HTML output is specifically what node's `http` module generates for some errors. Sentry does (or shouldn't) do this, and it's likely caused because the error is not catched. It bubbles up to Node.js error handling, which starts emitting a response, then the Nuxt error middleware starts emitting headers again ([here](https://github.com/nuxt/nuxt.js/blob/dev/packages/server/src/middleware/error.js#L15)). As node has finished writing the headers to the socket already, it can't emit them again, and panicks. To not leave the client in the dark, it generates a plain HTML page for the error that triggered the error handling in the first place.

I'll try to create a repro.

**Comment by rchl** [comment]
I can't reproduce that. I'm getting a normal Nuxt error and the error is also reported to Sentry correctly.

![Screenshot 2021-03-26 at 11 13 46](https://user-images.githubusercontent.com/153197/112616703-56227e00-8e24-11eb-96cd-2242ad2563e9.png)

Maybe try adding `config: { debug: true }` to module configuration and check if you see something relevant.

I can only think of this happening when there is some failure to report the error to Sentry that would make the app crash before reaching the normal error handler.

**Comment by Radiergummi** [comment]
hey @rchl I didn't get around to looking into this, so I'm going to close this issue for now. Still, thank you for your time!
