### ISSUE TITLE
console.error not showing in sentry

### ISSUE THREAD

**Issue by sebalaini-itm** [nuxt-community/sentry-module#281]
we are playing around with the sentry installation and we can't make work the unhandle error and make it show in the dashboard.

here my `nuxt.config.js` and you can see from the comments that I importing and implementing different things but not luck.

```
import { CaptureConsole } from '@sentry/integrations'
// import { Integrations } from '@sentry/tracing'


  /**
   * sentry
   */
  sentry: {
    dsn: 'https://...ingest.sentry.io/...', // Enter your project's DSN here
    config: {
      ignoreErrors: [
        'error 1',
        ....
      ],
      // integrations: [new Integrations.BrowserTracing()],
      integrations: [
      //   // new CaptureConsole({
      //   //   levels: ['error']
      //   // })
        new CaptureConsole()
      ],
      clientIntegrations: {
        CaptureConsole: {},
        Vue: { attachProps: true, logErrors: true }
      }
    }
  },
```

I inserted in a mounted hook in a component this
```
    console.error('test error')
    throw new Error('CaptureConsole')
```
and just the `throw new Error` it's being registered, the rest it's not showing even 404 images doesn't show in the dashboard.

**Comment by rchl** [comment]
Please check documentation carefully first. https://sentry.nuxtjs.org/

 - `clientIntegrations` is not a property of the `config` object
 - the `integrations` property should not be needed

**Comment by sebalaini-itm** [comment]
oh I see, my bad sorry.
I still can't have 404 shows in the dashboard, how do I enable them? 
what about this kind of errors?

**Comment by rchl** [comment]
A configuration like this should be enough:

```js
  sentry: {
    dsn: 'https://...ingest.sentry.io/...',
    clientIntegrations: {
      CaptureConsole: {},
    },
    config: {
      debug: true,
    }
  }
```

I've also added `config.debug` which might reveal the reason why the errors are not being reported if the issue is due to some other problem.

**Comment by sebalaini-itm** [comment]
thank you tomorrow I'll try it out :)

**Comment by sebalaini-itm** [comment]
now I have a lot of console messages in console and a warning but the errors I mentioned above are still missing in the dashboard.

```
  sentry: {
    dsn: 'http',

    config: {
      debug: true,
      // release: '1.1',  // this brake Nuxt build
      environment: process.env.NODE_ENV === 'development' ? 'development' : 'production',
      ignoreErrors: [
        'error 1',
        'error 2',
        ....
      ]
    },

    clientIntegrations: {
      CaptureConsole: {}
    },

    publishRelease: true,
    attachCommits: false,

    webpackConfig: {
      setCommits: {
        repo: 'myRepo/name',
        auto: true,
        commit: 'commitcode'
      }
    },

    tracing: {
      tracesSampleRate: 1,
      vueOptions: {
        tracing: true,
        tracingOptions: {
          trackComponents: true
        }
      },
      browserOptions: {
        tracingOrigins: [/^\//]
      }
    }
  },
  ```

- I have this warning `Sentry Logger [Warn]: Discarded session because of missing release` what does that mean? in my dashboard now I can see there is a release though I'm not sure from where it comes. It says 1.0.0.
- why the `release` in config break my nuxt build?
I'm using a bit of code that supposedly should work, or at least it's mentioned here https://github.com/nuxt-community/sentry-module/pull/123

The last question is how do I add the above errors (in the screenshot) and why I don't have 404 in the dashboard as well?

**Comment by rchl** [comment]
Check the console for any messages that might explain why errors are not reported.

As for 404, I don't think Sentry reports those so not sure why would you expect that.

Also please don't discuss multiple issues in the same place. Try to focus on solving the `console` errors not being reported for now.

**Comment by sebalaini-itm** [comment]
those errors are triggered when I click a button (as you can see from the screenshot it's coming from @glide ) and apparently now that I check in other browsers only chrome reports them, which may be the reason why I don't see them?

we would like to have 404 reported as we are not really in charge of them because we have a CMS-like setup, and someone can delete an image, or maybe it's not in the codebase and they reference something that doesn't exist anymore.

regarding the other errors should I open a new question?

**Comment by rchl** [comment]
This is not really a good place for support questions. You might want to switch to Discord - https://twitter.com/nuxt_js/status/1023853739738886144

**Comment by sebalaini-itm** [comment]
OK will close this and continue in Discord
