### ISSUE TITLE
Enable Suspect Commits

### ISSUE THREAD

**Issue by espensgr** [nuxt-community/sentry-module#282]
I'm trying to add commits to the release.
I have activated the `publishRelease` and `attachCommits` with `release` in `sentry.config`.
I tried to add `previousCommit` and `commit` to the `webpackConfig`, but i get a 403 not allowed even if i have the `SENTRY_AUTH_TOKEN` setup in my `.env` file.

Is this possible from within this plugin?

**Comment by rchl** [comment]
And this only happens with `attachCommits` enabled?

**Comment by espensgr** [comment]
Well when i removed the `webpackConfig` and just activated the `attachCommits` i didn't get an nuxt build error anymore. But i got an email from Sentry with a Github 404 permission access error.

Our repositories are in an organization, but i have added this repo to the Github integrations. And i have the Sentry.io third party app installed, and the third party access for Sentry on the organization.
And the release versions is setup with `projectname@*.*.*` instead of the default ref.

Don't know if anyone has a similar setup that has got this working?

**Comment by espensgr** [comment]
Well this has nothing to do with your plugin, i think i reconnected the integration and added a new auth_token with more scopes, then it worked.
Sorry for the inconvenience.

**Comment by rchl** [comment]
There is always room for improvement in the documentation I guess. PRs welcome. :)
