### ISSUE TITLE
Deploying with Heroku

### ISSUE THREAD

**Issue by chadwtaylor** [nuxt-community/sentry-module#283]
Getting the module worked perfectly from my local environment. 

When deploying to Heroku, it is failing when the `sentry-cli` interacts with the git repo (or so I think). Can you take a look at the error log from Heroku and see what the issue is? I've been Googling like crazy for the past two days and tried many possible fixes (eg: resetting auths, github permissions and resetting it, etc....) not getting anywhere with it. 

If someone can give insight/tip on what the issue is, I would truly appreciate it! :) 

Here's the output from Heroku (FYI `***` is used to mask sensitive info below):

```
ERROR in Sentry CLI Plugin: Command failed: /tmp/build_5410c600/node_modules/@sentry/cli/sentry-cli releases set-commits *** --auto
  INFO    2021-03-12 17:34:21.313599104 +00:00 sentry-cli was invoked with the following command line: "/tmp/build_5410c600/node_modules/@sentry/cli/sentry-cli" "releases" "set-commits" "***" "--auto"
  INFO    2021-03-12 17:34:21.492554660 +00:00 Resolving HEAD (***/webapp@HEAD)
error: could not find repository from '.'; class=Repository (6); code=NotFound (-3)
 FATAL  Nuxt build error
```

**Comment by chadwtaylor** [comment]
This is a follow up to my issue -- I had to update the `nuxt.config.js` file to reflect:

```jsonc
sentry: {
  dsn: process.env.SENTRY_DSN,
  attachCommits: false, // <- particularly this line was required to make the error in heroku go away
  publishRelease: true
}
```

I've no idea what the issue is with not being able to find the repository (it looked right) but I'm content with the above setup and leaving this issue open if someone wants to tackle this if anybody needs `attachCommits` to be `true`.

**Comment by rchl** [comment]
The error seems to indicate that there is no actual git repository during deploy. Just the file contents of the branch.

I haven't used Heroku personally so it's just a guess.

**Comment by rchl** [comment]
I'm not sure if I there are any actionable points here.

If I had Heroku deployment set up, I would maybe try checking if there is a `.git` directory at all during deployment and if so, if `git log` shows correct branch history **including tags**.

**Comment by theprivileges** [comment]
@rchl I can tell you that the nodejs [buildpack](https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-nodejs) in heroku does not include a `.git` directory.

**Comment by rchl** [comment]
Then it's expected that `attachCommits` doesn't work.

With the latest version of the module, you can manually pass the commit SHA to get commits to attach without a `.git` directory. See https://github.com/nuxt-community/sentry-module/issues/334#issuecomment-902572261
