### ISSUE TITLE
remove extra text from error

### ISSUE THREAD

**Issue by sebalaini-itm** [nuxt-community/sentry-module#284]
I contacted Sentry about why I can't see the suspect commit in the errors and they told me because it's due to an extra argument added to the error, do you know how can I remove the extra text `myComponent.vue?8655` that `?8655`?
is that some kind of configuration I can change?

my jenkins pipeline looks like this
```
                      sh 'SENTRY_NUXT_DSN=$SENTRY_NUXT_DSN SENTRY_RELEASE=$SENTRY_RELEASE SENTRY_ENVIRONMENT=$SENTRY_ENVIRONMENT SENTRY_TRACES_SAMPLE_RATE=$SENTRY_TRACES_SAMPLE_RATE BUILD_CACHE=true yarn run build'
                      sh './node_modules/.bin/sentry-cli releases set-commits $SENTRY_RELEASE --auto'
                      sh './node_modules/.bin/sentry-cli releases finalize $SENTRY_RELEASE'
                      sh './node_modules/.bin/sentry-cli releases deploys $SENTRY_RELEASE new -e $SENTRY_ENVIRONMENT'
```

and the config like this
```
  sentry: {
    dsn: process.env.NODE_ENV === 'development' ? null : process.env.SENTRY_NUXT_DSN,

    config: {
      debug: false,
      release: process.env.SENTRY_RELEASE ? process.env.SENTRY_RELEASE : 'test',
      environment: process.env.SENTRY_ENVIRONMENT ? process.env.SENTRY_ENVIRONMENT : 'local'
    },

    clientIntegrations: {
      CaptureConsole: {
        levels: ['error']
      }
    },

    publishRelease: true,
    attachCommits: true,
    sourceMapStyle: 'hidden-source-map',

    tracing: {
      tracesSampleRate: process.env.SENTRY_TRACES_SAMPLE_RATE ? process.env.SENTRY_TRACES_SAMPLE_RATE : 0,
      vueOptions: {
        tracing: true,
        tracingOptions: {
          trackComponents: true
        }
      },
      browserOptions: {
        tracingOrigins: [/^\//]
      }
    }
  },
```

**Comment by rchl** [comment]
Maybe try removing `sourceMapStyle` configuration so that it uses the default 'source-map' value?

I understand that it would be better not to reference source maps from built files but I believe I've tried that and it didn't work well.

**Comment by sebalaini-itm** [comment]
I will try, I was just following what the documentation say:
Note: Consider using `hidden-source-map` instead. For most people, that should be a better option but due to it being a breaking change, it won't be set as the default until next major release

**Comment by rchl** [comment]
Good point. Forgot about it.
But yeah, I think I've later discovered that it had some issues with mapping errors.
But interested to hear if it starts working for you if you change it.

**Comment by sebalaini-itm** [comment]
I'll close this for now and open a new one if I need more help :)
