### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by sp0ken** [nuxt-community/sentry-module#290]
This module is quite large already (it's the largest in my vendor chunk) and the addition of performance tracking added weight to the module.
I'm currently postponing the upgrade because of this issue.
Will the performance tracking script be integrated into the bundle if I deactivate the functionality?
Is there a way to trim the module size when building our app?

**Comment by rchl** [comment]
Those features should only increase the bundle size if they are actually enabled. So you shouldn't see much difference if you keep those disabled.

On a related note, enabling "lazy" will make the client-side bundle a lot smaller. The large chunk will be loaded asynchronously.

**Comment by rchl** [comment]
Hopefully, that answers your questions.

**Comment by sp0ken** [comment]
@rchl Thank you for the answer!
