### ISSUE TITLE
Regexs in config/serverConfig were saved as empty object in sentry.server.config.js

### ISSUE THREAD

**Issue by ding-js** [nuxt-community/sentry-module#307]
### Version
@nuxtjs/sentry: 5.0.3
nuxt: 2.15.4

### Sentry configuration
```js
{
  serverConfig: {
    ignoreErrors: [/Request failed with status code (401|403|404)/];
  }
}
```

### Steps to reproduce
set ignoreErrors with Regex

### What is Expected?
preserve Regex

### What is actually happening?
Regexs were saved as empty object in sentry.server.config.js

![image](https://user-images.githubusercontent.com/14885918/115387800-b92de780-a20d-11eb-99ed-845a3bb5a5c2.png)

I try to use `publicRuntimeConfig` and Regexs were passed correctly, maybe we should add a tip in docs?

**Comment by rchl** [comment]
This can be fixed: https://github.com/nuxt-community/sentry-module/pull/308
