### ISSUE TITLE
Webpack Sentry plugin for sourcemaps

### ISSUE THREAD

**Issue by simllll** [nuxt-community/sentry-module#31]
See https://github.com/40thieves/webpack-sentry-plugin

Would be great if this module does this also.

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sentry-module/issues/c25">#c25</a>)</em></sub></div>

**Comment by DiederikvandenB** [comment]
You should be able to just implement that here:
https://nuxtjs.org/faq/webpack-plugins

I don't even know if NuxtJS offers a hook for plugins to add Webpack plugins.

**Comment by manniL** [comment]
@DiederikvandenB It does!

**Comment by manniL** [comment]
You can use the `build.extend` function to do this.
Example package where I used that: https://github.com/Developmint/nuxt-svg-loader

**Comment by aldarund** [comment]
Ye, i use webpack sentry plugin personally and it work fine. Something like this inside build.extend
```
if (
        !ctx.isDev &&
        process.env.SENTRY_AUTH_TOKEN &&
        process.env.SENTRY_UPLOAD
      ) {
        const SentryPlugin = require('@sentry/webpack-plugin')
        if (ctx.isClient) config.devtool = '#source-map' // eslint-disable-line no-param-reassign
        config.plugins.push(
          new SentryPlugin({
            // release: revision,
            include: ['.nuxt/dist/client'],
            ignore: [
              'node_modules',
              '.nuxt/dist/client/img'
            ],
            configFile: '.sentryclirc',
            config: {
              environment: process.env.STAGE_ENV || 'development'
            }
          })
        )
      }
```

**Comment by DiederikvandenB** [comment]
I currently cannot spend any time on this. Since NuxtJS apparently offers a webpack plugin hook, as suggested by @manniL, I do think it is a good idea to implement it though. If anyone wants to contribute by submitting a PR, that would be great 👍

**Comment by DiederikvandenB** [comment]
For reference, I found a coffeescript version of a package which depends on this package which is doing exactly what you want:

https://github.com/BKWLD/blamo/blob/master/module/index.coffee#L51-L58

**Comment by simllll** [comment]
This is the config I'm using now, if someone is doing the same:
```if (!isDev) {
                if (isClient) {
                    config.devtool = '#source-map';
                }

                const SentryPlugin = require('@sentry/webpack-plugin')

                config.plugins.push(new SentryPlugin({
                    // Sentry options are required
                    include: ['.nuxt/dist/client'],
                    ignore: [
                        'node_modules',
                        '.nuxt/dist/client/img'
                    ],
                    configFile: '.sentryclirc',
                    config: {
                        environment: process.env.ENVIRONMENT || 'development'
                    }
                }));
            }
```

I guess the if for isclient isn't necessary and devtool  hidden-source-map would also be a good option. Need to look further into this.

Regards

**Comment by DiederikvandenB** [comment]
https://github.com/nuxt-community/sentry-module/tree/feature/sourcemaps

Finally, I found some time to take a look at this. In the `feature/sourcemaps` branchl you can see the most recent changes. I did some limited manual testing and it seems to work fine.

However, I did not test extensively enough to immediately merge this into the master branch. It would be helpful if others can check it out and see if it works as it should. And like always: PRs are appreciated.

**Comment by simllll** [comment]
Thanks @DiederikvandenB , some learnings I made in the meantime:
* do not upload sourcemaps on dev or test env (only production)
* do not upload sourcemaps when "analyze" is true.

**Comment by DiederikvandenB** [comment]
I feel like this feature will go unnoticed unless we merge it into the master branch.

For that reason, I will release v2.3 today, containing the sourcemap feature. I hope people will start playing with it more and report back with issues. Again, since we do not use NuxtJS ourselves anymore, it's difficult to test these changes against a production website.

**Comment by DiederikvandenB** [comment]
v2.3.0 has been released on NPM just now. I am going to close this issue to keep things organized.

If someone finds a bug in the new feature (it's definitely not perfect yet), please open a new issue.

**Comment by loomchild** [comment]
Works great, thanks a lot for implementing this feature.

I wrote a [little article explaining my specific configuration](https://medium.com/@loomchild/debugging-production-issues-with-sentry-and-nuxt-js-33f799c80d15?source=friends_link&sk=1ff5506d5fc2662142e17811f40a40c7), perhaps it would be useful for someone.

**Comment by JakubKoralewski** [comment]
@loomchild I am struggling to make source maps to work while having them deleted like you have.
I got it working when I didn't delete the source maps, but once I deleted them using `rimraf` after `nuxt generate` the source maps don't work on Sentry anymore.

Here are some logs:
```
10:12:02 PM: > Uploaded release files to Sentry
10:12:02 PM: > File processing complete
10:12:02 PM: Source Map Upload Report
10:12:02 PM:   Minified Scripts
10:12:02 PM:     ~/_nuxt/0379396e215d0524e143.js (sourcemap at 0379396e215d0524e143.js.map)
10:12:02 PM:     ~/_nuxt/2b4acd7b59084b5c1c85.js (sourcemap at 2b4acd7b59084b5c1c85.js.map)
10:12:02 PM:     ~/_nuxt/5e12c0ca71fc10f456d2.js (sourcemap at 5e12c0ca71fc10f456d2.js.map)
10:12:02 PM:     ~/_nuxt/91b1b29f5fb62f727962.js (sourcemap at 91b1b29f5fb62f727962.js.map)
10:12:02 PM:     ~/_nuxt/baefdf96f9d4b0121626.js (sourcemap at baefdf96f9d4b0121626.js.map)
10:12:02 PM:     ~/_nuxt/ce67c4a6ab8cd4cdf6da.js (sourcemap at ce67c4a6ab8cd4cdf6da.js.map)
10:12:02 PM:     ~/_nuxt/d2b0982a384a83fdff59.js (sourcemap at d2b0982a384a83fdff59.js.map)
10:12:02 PM:     ~/_nuxt/f92c31cd6ebf842a035e.js (sourcemap at f92c31cd6ebf842a035e.js.map)
10:12:02 PM:   Source Maps
10:12:02 PM:     ~/_nuxt/0379396e215d0524e143.js.map
10:12:02 PM:     ~/_nuxt/2b4acd7b59084b5c1c85.js.map
10:12:02 PM:     ~/_nuxt/5e12c0ca71fc10f456d2.js.map
10:12:02 PM:     ~/_nuxt/91b1b29f5fb62f727962.js.map
10:12:02 PM:     ~/_nuxt/baefdf96f9d4b0121626.js.map
10:12:02 PM:     ~/_nuxt/ce67c4a6ab8cd4cdf6da.js.map
10:12:02 PM:     ~/_nuxt/d2b0982a384a83fdff59.js.map
10:12:02 PM:     ~/_nuxt/f92c31cd6ebf842a035e.js.map
10:12:02 PM:   DEBUG   2019-06-27 20:12:02.956118068 +00:00 skipping update nagger because session is not attended
10:12:02 PM: * Closing connection 0
```

**Comment by loomchild** [comment]
Glad it finally worked. Maybe there are some changes in Nuxt or Sentry since my article. By default release is equal to commit hash - maybe there was some mismatch in your config.
