### ISSUE TITLE
environment config

### ISSUE THREAD

**Issue by MentalGear** [nuxt-community/sentry-module#312]
Thanks for this module!

Sentry has an "environment" variable that can be set, however it is nowhere found in the nuxt version of the module.
https://docs.sentry.io/platforms/javascript/configuration/options/#environment

Is this automatically set, or is there a reason we can't set it?

For example: I would need an dev, production and 'integration-testing' env.

**Comment by rchl** [comment]
See https://sentry.nuxtjs.org/sentry/options#config

**Comment by MentalGear** [comment]
Thanks @rchl 
Also, wrongly put all configurations into the config: {} object, cause they are both called configution in the guide and the setup page says:

```
{
  modules: [
    '@nuxtjs/sentry'
  ],
  sentry: {
    dsn: '', // Enter your project's DSN here
    config: {}, // Additional config
  }
}
```

Tried to make it a bit clearer for others with this PR:
https://github.com/nuxt-community/sentry-module/pull/313
