### ISSUE TITLE
How to set sentry log level?

### ISSUE THREAD

**Issue by denielaa** [nuxt-community/sentry-module#319]
In sentry docs there is a configuration to set the minimum Level to be sent. 
https://docs.sentry.io/platforms/node/usage/set-level/

Is there a way to set this?
I have checked the documentation, but I couldn't find it. I might miss it

**Comment by rchl** [comment]
The `Sentry` object in that documentation is equivalent to `process.sentry` in server middleware and `$sentry` object in template/script block.

**Comment by denielaa** [comment]
thanks for the answer
