### ISSUE TITLE
Runtime DSN - Configuration & Documentation

### ISSUE THREAD

**Issue by appinteractive** [nuxt-community/sentry-module#323]
Hey @rchl do anyone know how to setup the sentry-module to work properly with runtime DSN or how to debug that thing? It works locally but not in production, no error, no message, nothing. Its deployed inside a docker container with kubernetes and consumes a dynamic env var with the DSN.

Sadly the documentation is very thin when it comes to configuration as there are only snippets shown, but never the context.

Nuxt config:
```
  publicRuntimeConfig: {
    SENTRY_DSN: process.env.SENTRY_DSN,
    sentry: {
      dsn: process.env.SENTRY_DSN,
      environment: process.env.NODE_ENV,
      config: {},
    },
  },
  privateRuntimeConfig: {},

  sentry: {
    dsn: process.env.SENTRY_DSN,
    tracing: {
      tracesSampleRate: 1.0,
      vueOptions: {
        tracing: true,
        tracingOptions: {
          hooks: ['mount', 'update'],
          timeout: 2000,
          trackComponents: true,
        },
      },
      browserOptions: {},
    },
  }, 
```
The env var is there when i echo it before starting the service

The documentation does not give any information on how to or what is possible to configure with the runtime config. Its really confusing for me.

**Comment by sPaCeMoNk3yIam** [comment]
Ran into the exact same limitation.

**Comment by rchl** [comment]
The documentation might be scarce but you still didn't read it properly. :)

It says at https://sentry.nuxtjs.org/sentry/runtime-config/ that

> only the `config`, `clientConfig` and `serverConfig` options can be configured using the runtime config.

and yet your config looks like this:

```js
  publicRuntimeConfig: {
    SENTRY_DSN: process.env.SENTRY_DSN,
    sentry: {
      dsn: process.env.SENTRY_DSN,
      environment: process.env.NODE_ENV,
      config: {},
    },
  },
```

The only thing valid/supported here is the `config` object but it's empty. You want something like:

```js
  publicRuntimeConfig: {
    sentry: {
      config: {
        dsn: process.env.SENTRY_DSN,
        environment: process.env.NODE_ENV,
      },
    },
  },
```

**Comment by sPaCeMoNk3yIam** [comment]
> The documentation might be scarce but you still didn't read it properly. :)
> 
> It says at https://sentry.nuxtjs.org/sentry/runtime-config/ that
> 
> > only the `config`, `clientConfig` and `serverConfig` options can be configured using the runtime config.
> 
> and yet your config looks like this:
> 
> ```js
>   publicRuntimeConfig: {
>     SENTRY_DSN: process.env.SENTRY_DSN,
>     sentry: {
>       dsn: process.env.SENTRY_DSN,
>       environment: process.env.NODE_ENV,
>       config: {},
>     },
>   },
> ```
> 
> The only thing valid/supported here is the `config` object but it's empty. You want something like:
> 
> ```js
>   publicRuntimeConfig: {
>     sentry: {
>       config: {
>         dsn: process.env.SENTRY_DSN,
>         environment: process.env.NODE_ENV,
>       },
>     },
>   },
> ```

Yes, that worked for me, didn't come back here to report, before this answer. But one thing to keep in mind is that you still need to provide a `dsn` within the `sentry` part of your root config as there is no env (`SENTRY_DSN`) set. I gave it a value of `will_get_overridden`.

```
{
  sentry: {
    dsn: 'will_get_overridden',
  },

  publicRuntimeConfig: {
    sentry: {
      config: {
        dsn: process.env.SENTRY_DSN,
      },
    },
  },
}
