### ISSUE TITLE
orgSlug option

### ISSUE THREAD

**Issue by MentalGear** [nuxt-community/sentry-module#324]
### Is your feature request related to a problem? Please describe.
Many commands require to specify the organization and project to work with, but there's no option in sentry nuxt to define it.
Source: https://docs.sentry.io/product/cli/configuration/

### Describe the solution you'd like
An option property with the name "orgSlug".

### Describe alternatives you've considered
- Setting env vars, but that's something that can't be always done depending on context, or it becomes a redundant config if the value doesn't change.
- properties file or cli --org flag, which both can't be used via the plugin

**Comment by MentalGear** [comment]
For example, running the following config:

```js
  sentry: {
    disabled: publicEnvVars.APP_CONTEXT === 'development', // will be false for tests which allows integration test
    dsn: 'MASKED',

    // release: is automatically inferred from the local repo .package.json unless specified manually,
    publishRelease: true,
    repo: 'MASKED',
    attachCommits: true,
    sourceMapStyle: 'hidden-source-map',
    config: {
      // native swentry config Options
      // https://docs.sentry.io/platforms/javascript/guides/vue/configuration/options/
      environment: publicEnvVars.APP_CONTEXT,
      /* eslint-disable object-shorthand */
      beforeSend: function (event) {
        // Check if it is an exception, and if so, show the report dialog
        if (event.exception) {
          // native Sentry JS Bug Reporter
          // https://docs.sentry.io/platforms/javascript/guides/vue/enriching-events/user-feedback/
          // eslint-disable-next-line no-undef
          Sentry.showReportDialog({ eventId: event.event_id })
        }
        return event
      },
      /* eslint-enable */
    },
```

I'm getting nuxt failing with:

```console
ERROR in Sentry CLI Plugin: Command failed: /Users/Tom/Desktop/aitools/node_modules/@sentry/cli/sentry-cli releases new e972fa699bc74620ed2434996e614239734891e0
error: An organization slug is required (provide with --org)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
```

**Comment by rchl** [comment]
> * properties file or cli --org flag, which both can't be used via the plugin

The `.sentryclirc` works and that's what I'm personally using.

But I agree that the situation is not ideal right now and it should be possible to pass those as options.

Just gonna clarify your remark about "Many commands require...". From the functionalities provided by this module, only the `publishRelease` functionality requires those to be provided.

**Comment by MentalGear** [comment]
Thanks for the swift reply and the `.sentryclirc` hint, it works.

```shell
export SENTRY_ORG=ORGNAME
```

Maybe any idea why it's only an issue when using static mode?

> Just gonna clarify your remark about "Many commands require...". From the functionalities provided by this module, only the publishRelease functionality requires those to be provided.

It's actually a quote from the sentry guide: https://docs.sentry.io/product/cli/configuration/#sentry-cli-working-with-projects

**Comment by rchl** [comment]
> I added it like this in the root of the project. (also tried it without the `export`)
> 
> ```shell
> export SENTRY_ORG=orgname
> ```
> 
> But it doesn't work for me.

This is from the section in the documentation on how to just set it as environment variable.

For the configuration file you need to follow this syntax:
```
[auth]
token=your-auth-token
```

**Comment by MentalGear** [comment]
Ah, strange that this part requires authentication. Any idea though why only static mode seems to require the org for publishRelease ( I used it previously without a problem ) ?

**Comment by rchl** [comment]
I have not looked into that.

Are you saying that during `nuxt generate` it would complain about missing org but not when using `nuxt build` or `nuxt dev`?

Is this sentence from the documentation relevant here?

> Note that releases are only submitted to Sentry when (options.publishRelease && !isDev) is true.Note that releases are only submitted to Sentry when (options.publishRelease && !isDev) is true.

**Comment by MentalGear** [comment]
Thanks for your help. Indeed, `generate` and `build` are not different, it probably was as of `(options.publishRelease && !isDev)` that made it behave differently during dev.

I was able to make it work with
```
export SENTRY_AUTH_TOKEN
```
instead of
```
[auth]
token=your-auth-token
```

Also I have not found a way to set `SENTRY_AUTH_TOKEN` (required for publishRelease) via plugin options or config object, only by way of env, rc or properties file. Maybe worth a note in the guide that a rc file is required at least as long as `SENTRY_ORG` and `SENTRY_AUTH_TOKEN` has no plugin option.

**Comment by rchl** [comment]
The properties file I've posted was just a basic example from the sentry docs. You'd want more something like this if you'd go that route:

```
[auth]
token=...

[defaults]
url=...
org=...
project=...
```

> Also I have not found a way to set `SENTRY_AUTH_TOKEN` (required for publishRelease) via plugin options or config object

That's the part that should be fixed.

**Comment by rchl** [comment]
With latest release the `publishRelease` can be an object that accepts all those settings. See more info and an example at https://sentry.nuxtjs.org/sentry/options#publishrelease.
