### ISSUE TITLE
ERROR in Sentry CLI Plugin: set-commit errors

### ISSUE THREAD

**Issue by MentalGear** [nuxt-community/sentry-module#328]
Getting a lot of these. At first I thought it was because I tried deploying branches with the same commit state more than once, yet it now also happens for fresh deploys. Any idea maybe what the issue might be ?

```
1:01:21 PM: [fatal] Nuxt build error
1:01:21 PM:   ERROR in Sentry CLI Plugin: Command failed: node_modules/@sentry/cli/sentry-cli releases set-commits fce7c0ff8b1359290bb8ad4e6562dd57510b76ae --auto
1:01:21 PM:   error: Could not find the SHA of the previous release in the git history. If you limit the clone depth, try to increase it. Otherwise, it means that the commit we are looking for was amended or squashed and cannot be retrieved. Use --ignore-missing flag to skip it and create a new release with the default commits count.
```

Config:
```js
  sentry: {
    disabled: publicEnvVars.APP_CONTEXT === 'development', // will be false for tests .e.g unit, integration
    dsn: 'MASKED',

    // release: is automatically inferred from the local repo .package.json unless specified manually,
    repo: 'MASKED',
    publishRelease: true,
    attachCommits: true,
    sourceMapStyle: 'hidden-source-map',

    // --- native sentry config Options
    config: {
      environment: publicEnvVars.APP_CONTEXT,
      // -> NOTE: additional config in ~.sentryclirc
      // as 'auth' and 'orgSlug' can't be yet set here
    },
}
```

**Comment by MentalGear** [comment]
`ignore-missing` flag has only been recently added to sentry (11 days ago).
https://github.com/getsentry/sentry-cli/pull/963

**Comment by rchl** [comment]
Can you reproduce when running `npx @sentry/cli releases propose-version` in your repo? If so then it doesn't seem like a problem specific to this module.

We could of course add support for `ignore-missing` but still you would probably want to resolve your issue with detecting releases.

**Comment by MentalGear** [comment]
`npx @sentry/cli releases propose-version` runs fine with consistent output.

Mh, maybe it has something to do with that I merge commits from my `dev` branch into the `stage` branch (which netlify deploys).

**Comment by rchl** [comment]
So you are getting the error on netlify?
Can you reproduce locally by running that command on stage branch? If not then maybe on netlify there is no actual git repository when building Nuxt. It might be doing just fefching a single commit.

**Comment by MentalGear** [comment]
Thanks, it seems to work when running locally. Although netlify is also linked with my github account, the culprit may lie there.

**Comment by saniales** [comment]
I have the same issue and I used once git commit --amend, I need to be able to set this value, otherwise my Ci is blocked

**Comment by rchl** [comment]
With https://github.com/nuxt-community/sentry-module/releases/tag/v5.1.2 the `publishRelease` accepts all options that the CLI accepets so you can set "ignore missing" like that:

```js
  sentry: {
    // ...
    publishRelease: {
      setCommits: {
        ignoreMissing: true
      }
    }
  }
```

BTW. `webpackConfig` is now deprecated and `publishRelease` takes over its role.
