### ISSUE TITLE
How to use sentry on vuex action (serverside)

### ISSUE THREAD

**Issue by eseceve** [nuxt-community/sentry-module#33]
Hi, I trying to use `$sentry` from a vuex action but it's `undefined` when action is called from `asyncData`

`store/index.js`
```javascript
async foo({ commit, state }) {
   const response = await this.$axios.$get('/foo/')
   this.$sentry.captureMessage('Test foo', { extra: { response }})
}
```
`package.json`
```
"@nuxtjs/sentry": "^2.0.0",
"nuxt": "^2.2.0",
```

`nuxt.config.js`
```javascript
  // read dsn from process.env.SENTR_DSN
  sentry: {
    disabled: false,
    config: {
      debug: true
    }
  }
```

**Comment by DiederikvandenB** [comment]
Hi. See if this helps you out: https://github.com/nuxt-community/sentry-module/issues/19#issuecomment-384830231

**Comment by eseceve** [comment]
After I update Nuxt to 2.43 and **@nuxt/sentry to 2.3.1** `$raven` nor `$sentry` aren't available on Store's actions.
How can I set an user in Sentry from my Store? I tried with this but doesn't works

```javascript
// store/user.js
export const actions = {
  async getProfile({ commit }, data) {
    const user = this.app.$axios.$get('/me/')
    this.app.$sentry.configureScope(scope => {
      scope.setUser(user)
    })
    // this.app.$sentry and this.$sentry are undefined
  }
}
```

**Comment by drewbaker** [comment]
For future people finding this, this works for me with v4.0.3 as a Vuex action

```
    async GET_SELF({ commit }, email) {
        // Set user scope for Sentry
        this.app.$sentry.configureScope(function(scope) {
            scope.setUser({ email: email })
        })
        // Do your other stuff here (for me, that was Apollo request for user data)
    }
```

**Comment by Webbist-dev** [comment]
> Also for future people finding this, 2020 was a wild year, I hope the future is better.

this aged like milk
