### ISSUE TITLE
Strange post requests to sentry

### ISSUE THREAD

**Issue by KStenK** [nuxt-community/sentry-module#330]
Hi guys!

Any idea why that module is making POST requests from the client-side to the URL: 

https://xxx.ingest.sentry.io/api/xxx/envelope/?sentry_key=xxx&sentry_version=7

Every time I route to a new page it makes request a twice or once when I refresh the page.
I'm using default settings, nothing extra.
Is that necessary or is it possible to turn it off somehow?

**Comment by rchl** [comment]
`autoSessionTracking` option. See https://github.com/nuxt-community/sentry-module/releases/tag/v5.0.0 for more info.

It's a Sentry config option (rather than this module's option) and it's enabled by default.

**Comment by KStenK** [comment]
That worked. Thank you.
