### ISSUE TITLE
Unable to publishRelease and attachCommits when git folder is not in Docker container

### ISSUE THREAD

**Issue by dr808** [nuxt-community/sentry-module#334]
### Version
@nuxtjs/sentry: @nuxtjs/sentry@5.1.1
nuxt: 2.15.8

### Sentry configuration
```
  sentry: {
    dsn: process.env.SENTRY_DSN || '',
    publishRelease: process.env.SENTRY_PUBLISH_RELEASE || false,
    attachCommits: true,
    sourceMapStyle: 'hidden-source-map',
    repo: process.env.SENTRY_RELEASE_REPO || '',
    config: {
      project: process.env.SENTRY_PROJECT || '',
      release: process.env.SENTRY_RELEASE || '',
    },
  },
```

### Reproduction Link
N/A
### Steps to reproduce
Setup Sentry with git integration
Create docker container
Add `.git` to `.dockerignore`
Set `publishRelease: true` `attachCommits: true`
Build container

See failure 👎 
```
[...]
sentry-cli was invoked with the following command line: "/app/node_modules/@sentry/cli/sentry-cli" "releases" "set-commits" "cd53f03bdaa7513ecebe18c4bdbd74e100648c81" "--auto"
[...]
`error: could not find repository from '.'; class=Repository (6); code=NotFound (-3)`
```

Removing `.git` from `.dockerignore` (adding `.git` dir to the container) solves the problem but obviously that cannot be the solution.
### What is Expected?
The command should look something like `sentry-cli releases set-commits $RELEASE $REPO_NAME@$REVISION`
`--auto` should not be when `repo` is explicitly set in config.
### What is actually happening?
Sentry is unable to determine the git repo details when not inside a git repo. This should be resolved by adding `$REPO_NAME@$REVISION` to the `sentry-cli` `releases` command but that's not what happens. I assumed that's what `repo` in `nuxt.config.js` does but at this point I'm not sure what it does, if anything.

**Comment by rchl** [comment]
I think that's because you've enabled `attachCommits`. If you don't have git repo when building then you can't attach commits.

**Comment by dr808** [comment]
Ok, maybe I misunderstood the `repo` option and thinking about it again obviously that wouldn't explicitly set the commit.

Having said that, here is what the docs say:

From [https://docs.sentry.io/product/releases/suspect-commits/](https://docs.sentry.io/product/releases/suspect-commits:)
"For more control over which commits to associate, or if you're unable to execute the command inside the repository, you can manually specify a repository and range."

Any way to change the command and explicitly set it on build? My current workaround is to add `RUN rm -rf .git` to our Dockerfile.

**Comment by rchl** [comment]
With the latest version of this module you can pass all those options through the `publishRelease` option. See https://sentry.nuxtjs.org/sentry/options#publishrelease

I think you would then need to also unset "auto" like so:

```
    sentry: {
          publishRelease: {
            // ...
            setCommits: {
                auto: false,
                repo: '<repo>',
                commit: '<commit>',
            },
        },
    },
```

**Comment by dr808** [comment]
That worked perfectly. Thank you!
