### ISSUE TITLE
Beginner questions / why is sentry not tracking events?

### ISSUE THREAD

**Issue by iparker** [nuxt-community/sentry-module#346]
Hello,

I try to integrate sentry into an nuxt application but I don't see any events online. Also I see no requests send to sentry in the network requests. I installed the module and set the dns in nuxt.config but it does not work.

So my questions are:

1.) Is this sentry module also working in dev-environment? 

2.) Which kind of project/integration type do I have to choose in sentry? VueJS or Other? I think "Other" is correct, I tried both but it isn't working.

3.) Will sentry also log all errors displayed in console or just exceptions I send to sentry (like this.$sentry.captureException(new Error('example')); )? Should be every error in console automatically appear in sentry?

Do I need to enable any special option or do something else?

Thanks for some help with this!

Best regards,

Timo

**Comment by rchl** [comment]
1) It's enabled in development also, unless explicitly disabled
2) The type of integration on Sentry side most likely doesn't matter. It's most just a cosmetic choice.
3) This module captures all unhandled exceptions so including the ones that show up in the console.

This modules prints some logs on starting Nuxt app. What do those say?

**Comment by iparker** [comment]
Damn - you are right! I placed the sentry-config in nuxt.config in wrong order. Fixed this it is instantly working! Thanks a lot!

But one more question:

Currently I don't see my console-errors in sentry. I have console output like this:

GET http://localhost:1337/uploads/home_hero_a654f8a229.jpg 404 (Not Found) --> Image not found

[Vue warn]: Unknown custom element: <vuetify-google-autocomplete> - did you register the component correctly? For recursive components, make sure to provide the "name" option.  --> Problem with vue component

Unchecked runtime.lastError: The message port closed before a response was received. --> Another output in console

Is there a way to get this output also in sentry? Or what kind of errors are tracked in sentry?

**Comment by rchl** [comment]
Looks like you are hitting #245 - known issue with exceptions within fetch not being captured.

**Comment by iparker** [comment]
Again thanks a lot for your quick reply! 

The issue with exceptions in fetch is an important point. 

And can you tell me something about the other points? Should an "not found"-get-request or an vue warning be visible in sentry?

My thought was that I will see all the output from the console in sentry. Currently I just see type errors.

**Comment by rchl** [comment]
Console logs are not captured by default. You can configure a `CaptureConsole` integration if you want that. See https://sentry.nuxtjs.org/sentry/options#clientintegrations

**Comment by iparker** [comment]
Great - thanks a lot! Now I see the console output in sentry. Thanks a lot!
