### ISSUE TITLE
Server error not appearing on Sentry

### ISSUE THREAD

**Issue by viktor-anyvan** [nuxt-community/sentry-module#347]
Hi,

We tried all type of configurations, ENV, nuxt.config ["@nuxtjs/sentry", {...}], also simply sentry: {} and runtimeConfig as well.

No luck, none of the errors are appearing on Sentry (when there is a server error). SSR enable and simply adding {{rrrr.rrrr}} to a template.

Any advice what to check/try?

Thanks

**Comment by viktor-anyvan** [comment]
@rchl Any advice?

**Comment by rchl** [comment]
- Check the terminal logs on starting Nuxt. They tell you whether sentry is enabled.
- Post your sentry configuration. The DSN option is required at least.
- Create minimal project that reproducs.

**Comment by viktor-anyvan** [comment]
First of all thank you for the response.

- Terminal is saying sentry is enabled (client and server)
- DSN is there (for all the configuration versions what i mentioned and tried)
- Will try somewhere

Additional details if that helps:
Was looking the .nuxt/dist folder. In server.js was doing console.log for "process.sentry" and it was undefined, how is that? Is taht normal?
In .nuxt sentry.server.config.js i see the proper dsn set and also environment: "production". In sentry.server.js I see the code what after appearing in server.js what i was mentioned before, but because "const sentry = process.sentry || {}" it will inject simply the {}

**Comment by viktor-anyvan** [comment]
@rchl after working with Sentry in the last few days found "Sentry.close".

Wanted to try this somehow and added to the "render:errorMiddleware". In the Nuxt docs there is actually a link https://github.com/nuxt-community/sentry-module/blob/v4.0.3/lib/module.js#L151 but I guess in an actual crash this will not finish. So i tried to add:
`hooks: {
    render: {
      errorMiddleware(app) {
        Sentry.close(2000).then(function(app) {
          app.use(Sentry.Handlers.errorHandler())
        })
      },
    },
  }`
to the Nuxt config and finally was able to see the error on Sentry.

Any ideas about this? Also not sure for what kind of errors actually this hook is going to run, as this "Sentry.close" should only happen when the app is not going to run anymore (shut down). Not sure what does this mean on server level.

Thanks for you help in advance.

**Comment by rchl** [comment]
You can try to enable debug option. It should make Sentry print some information to the console if the error is ignored after being triggered.

```
  sentry: {
    dsn: '...,
    config: {
      debug: true
    }
  }
```

**Comment by rchl** [comment]
Well, I can't help more with the information I have. You have to either figure it out on your own or create a small repo that reproduces (I can use my own DSN).

Note that there is known issue with errors triggered within a `fetch()` so those are not caught.

**Comment by viktor-anyvan** [comment]
It's not in "fetch". What if you add to one off your existing projects (sorry will try to make an empty nuxt project with sentry-module at some point) and if you try to print {{notdefinedObj.name}} on a page. Important part is that it's happening with build and start (fine with dev), and now I'm also in production mode.

**Comment by rchl** [comment]
For me such a simple cases work (regardless of `nuxt start` or `nuxt dev`).

**Comment by viktor-anyvan** [comment]
@rchl finally found the reason.

It is related to where we add the module in nuxt config, in docs it is mentioned it should be added to modules and not to buildModules (where we have it).

Why? Because we would like to use https://macopedia.com/blog/news/how-to-reduce-the-size-of-an-application-based-on-nuxtjs
and for other modules like "@nuxtjs/auth" and few others what we are using (in docs they are saying those should be in modules as well) we added them to buildModules and are working without a problem.

Any suggestions? Right now the only option what I see after build when we are removing node_modules and add that one particular package to run nuxt-start we have to add @nuxtjs/sentry as well.

**Comment by rchl** [comment]
Yes, this module needs to be in `modules` since it initializes process.sentry while initializing the module.
And you also need some other packages that the module references like `@sentry/*` and some lodash ones.
There is no way around it.

I find https://macopedia.com/blog/news/how-to-reduce-the-size-of-an-application-based-on-nuxtjs to be quite an ill advice. It doesn't improve anything for the end user and makes it easy to break things unless you know exactly how each module works (even then a new version might break).
