### ISSUE TITLE
clientIntegrations not working properly

### ISSUE THREAD

**Issue by sebalaini-itm** [nuxt-community/sentry-module#350]
I'm trying to configure some options in the `clientIntegrations` but they don't seem to be working properly.

This is my config:
```
  sentry: {
    // lazy cannot be enabled or will brake the tracing feature.
    lazy: false,
    dsn: process.env.NODE_ENV === 'development' ? null : process.env.SENTRY_NUXT_DSN,

    config: {
      debug: true,
      release: process.env.SENTRY_RELEASE ? process.env.SENTRY_RELEASE : 'test',
      environment: process.env.SENTRY_ENVIRONMENT ? process.env.SENTRY_ENVIRONMENT : 'local'
    },

    // ignoreErrors: [
     // /.*Non-Error promise rejection captured with*/,
     // /.*[object Event]*/,
     // /.*<unknown>*/,
     // /.*Missing external script*/,
     // /.*ECONNRESET*/,
     // /.*TypeError: document.head.append is not a function*/
    // ],
    
    clientIntegrations: {
      CaptureConsole: {
        levels: ['error']
      },
      InboundFilters: {
        ignoreErrors: [
          /.*Non-Error promise rejection captured with*/,
          /.*[object Event]*/,
          /.*<unknown>*/,
          /.*Missing external script*/,
          /.*ECONNRESET*/,
          /.*TypeError: document.head.append is not a function*/
        ]
      },
      ReportingObserver: {
        types: ['crash']
      }
    },

    serverIntegrations: {
      CaptureConsole: {
        levels: ['error']
      }
    },

    publishRelease: true,
    attachCommits: true,

    tracing: {
      tracesSampleRate: process.env.SENTRY_TRACES_SAMPLE_RATE ? Number(process.env.SENTRY_TRACES_SAMPLE_RATE) : 0,
      vueOptions: {
        tracing: true,
        tracingOptions: {
          trackComponents: true
        }
      },
      browserOptions: {
        tracingOrigins: [/^\//]
      }
    }
  },
```

The `InboundFilters` and `ReportingObserver` don't work at all, I can still see them reported in the dashboard, how can I fix it?

**Comment by rchl** [comment]
As for `InboundFilters` the [Sentry documentation](https://docs.sentry.io/platforms/javascript/configuration/integrations/default/#inboundfilters) says to:

> To configure this integration, use ignoreErrors, denyUrls, and allowUrls SDK options directly. Keep in mind that denyURL and allowURL work only for captured exceptions, not raw message events.

As far as `ReportingObserver`, how are you triggering the "reporting observer API" crash exactly? I'm not sure what kind of crashing that integration handles. For normal exceptions you don't need that integration.

**Comment by sebalaini-itm** [comment]
OK, so the correct way to do it it's to remove the `InboundFilters` from the `clientIntegrations` and use `ignoreErrors` in the `config` object?

At some point, I tried that way as well but errors like this one were still there
![image](https://user-images.githubusercontent.com/61748264/134460785-406e7cd3-8a13-4efc-850e-1e45ad8ad8f9.png)

About the `ReportingObserver` I'm not sure how they are triggered, TBH I would be more than happy to remove all notifications about them, I set only `crash` to remove all the `ReportingObserver` info notifications it's returning in the dashboard
![image](https://user-images.githubusercontent.com/61748264/134461202-73e09069-bc26-4a46-b3e6-d51f4d68e4e5.png)

**Comment by rchl** [comment]
Something like this should work as far as I can see:

```js
sentry: {
  config: {
    ignoreErrors: [
      'Non-Error promise rejection captured with',
    ]
   }
}
```

If not then sorry but I can't diagnose the problem more without having a repo that reproduces.

**Comment by sebalaini-itm** [comment]
After a couple of days in master and the cache fully expired seems the code it's now working, though this one `Non-Error promise rejection captured with` doesn't seem to work for some reason, I'm trying to add it directly to the Sentry UI filter inbound section.
