### ISSUE TITLE
Sentry update

### ISSUE THREAD

**Issue by sebalaini-itm** [nuxt-community/sentry-module#351]
Is there a date for the next update? seems that has been opened a while ago https://github.com/nuxt-community/sentry-module/pull/345 but it hasn't been merged yet, there are already 2 minor releases between this package and Sentry

**Comment by rchl** [comment]
`npm update @nuxtjs/sentry` should update the Sentry dependencies since those are not pinned.

If you are using npm 6 (rather than 7) then that will likely not work but cause uninstall and install this package again to do the same.

**Comment by sebalaini-itm** [comment]
That's good to know :) we are using `yarn` will give it a try and check that everything still working as expected.
