### ISSUE TITLE
'nuxt generate' finished but did not exit after 5s

### ISSUE THREAD

**Issue by tdwells90** [nuxt-community/sentry-module#352]
### Version
@nuxtjs/sentry: 5.1.3
nuxt: 2.15.7

### Sentry configuration

```
  sentry: {
    dsn: '<dsn here>',
    lazy: true,
    disabled: !!process.env.ENV === 'dev',
    publishRelease: true,
    tracing: {
      tracesSampleRate: 0.05
    },
    config: {
      environment: process.env.ENV,
      release: `app-ui@${pkg.default.version}`,
      dsn: '<dsn here>',
      disabled: !!process.env.ENV === 'dev'
    }
  }
```

### Steps to reproduce

It's happening for me on fresh installs with create-nuxt-app, existing projects etc with `target: 'static'` set and running `yarn generate` command. This is only happening with this module installed and different Sentry configurations don't seem to make a difference.

Here are my dependencies on the fresh install:

```
  "dependencies": {
    "@nuxt/content": "^1.14.0",
    "@nuxtjs/axios": "^5.13.6",
    "@nuxtjs/pwa": "^3.3.5",
    "@nuxtjs/sentry": "^5.1.3",
    "core-js": "^3.15.1",
    "nuxt": "^2.15.7"
  },
  "devDependencies": {
    "@babel/eslint-parser": "^7.14.7",
    "@nuxt/types": "^2.15.7",
    "@nuxt/typescript-build": "^2.1.0",
    "@nuxtjs/eslint-config-typescript": "^6.0.1",
    "@nuxtjs/eslint-module": "^3.0.2",
    "@nuxtjs/tailwindcss": "^4.2.0",
    "@vue/test-utils": "^1.2.1",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "^27.0.5",
    "eslint": "^7.29.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-nuxt": "^2.0.0",
    "eslint-plugin-vue": "^7.12.1",
    "jest": "^27.0.5",
    "postcss": "^8.3.5",
    "prettier": "^2.3.2",
    "ts-jest": "^27.0.3",
    "vue-jest": "^3.0.4"
  }
```

### What is Expected?

Not to receive the warning, which will be fatal in Nuxt 3.

### What is actually happening?

The project builds currently with a warning but will be fatal in Nuxt 3 which is due for release in 12 days.

**Comment by rchl** [comment]
#353 should fix.

It appears that the `tracing` functionality is what makes it block the process.

**Comment by tdwells90** [comment]
> #353 should fix.
> 
> It appears that the `tracing` functionality is what makes it block the process.

It's worth mentioning it was doing this with `tracing` set to `false` as well. If your fix works, then that was quick! Thanks :)

**Comment by rchl** [comment]
I've mentioned tracing because that's what reproduced for me but the fix is generic enough that it should cover all cases.

**Comment by mjkhonline** [comment]
> If you are sure that this module is the culprit then I can have a look if you provide a reproduction

Thanks buddy. I have double checked everything. It seems that the issue is not related to this module. I have to investigate furthermore.
