### ISSUE TITLE
Sentry doesnt report server side errors

### ISSUE THREAD

**Issue by ortonomy** [nuxt-community/sentry-module#359]
### Version
@nuxtjs/sentry: `^5.13.6`
nuxt: `2.15.7`

### Sentry configuration
```
sentry: {
      dsn: process.env.SENTRY_DSN || null,
      debug: devMode,
    },
```

### Reproduction Link
private repo, can't do

### Steps to reproduce
check out of `sentry.server.config.js` in the `.nuxt` build folder. DSN is missing:

`
/* eslint-disable */
export const config = {"environment":"development","release":"d83291467b1702f2e8c933a096d4cd84e49dc965"}
`

### What is Expected?

`process.sentry.captureException` works

### What is actually happening?

doesn't work

**Comment by rchl** [comment]
You could check whether on the client side a network request is dispatched to Sentry endpoint on triggering an eror.

**Comment by ortonomy** [comment]
Log even says it's active:

```
✔ Sentry reporting is enabled (client side: enabled, server side: enabled)
Sentry Logger [Log]: Integration installed: InboundFilters            20:32:37
Sentry Logger [Log]: Integration installed: FunctionToString          20:32:37
Sentry Logger [Log]: Integration installed: Console                   20:32:37
Sentry Logger [Log]: Integration installed: Http                      20:32:37
Sentry Logger [Log]: Integration installed: OnUncaughtException       20:32:37
Sentry Logger [Log]: Integration installed: OnUnhandledRejection      20:32:37
Sentry Logger [Log]: Integration installed: LinkedErrors              20:32:37
Sentry Logger [Log]: Integration installed: Dedupe                    20:32:37
Sentry Logger [Log]: Integration installed: ExtraErrorData            20:32:37
Sentry Logger [Log]: Integration installed: RewriteFrames             20:32:37
Sentry Logger [Log]: Integration installed: Transaction               20:32:37
```

**Comment by ortonomy** [comment]
> You could check whether on the client side a network request is dispatched to Sentry endpoint on triggering an error.

Yes, it is!

**Comment by ortonomy** [comment]
It must be ignoring the requests.... I'll have to see why

**Comment by rchl** [comment]
Based on the comments I'm assuming it was not a module's issue.
