### ISSUE TITLE
ERROR in Sentry CLI Plugin

### ISSUE THREAD

**Issue by madsh93** [nuxt-community/sentry-module#362]
@nuxtjs/sentry: 5.1.4
nuxt: 2.15.7

### Sentry configuration
````
  sentry: {
    dsn: process.env.SENTRY_DNS,
    lazy: false,
    sourceMapStyle: 'hidden-source-map',
    disabled: isDev,
    publishRelease: {
      setCommits: {
        auto: true
      }
    }
  },
````

### Steps to reproduce
Deploy on Vercel

### What is Expected?
No errors

### What is actually happening?
I get following error: 
![image](https://user-images.githubusercontent.com/8860723/139510105-a58c5c7e-01e0-4050-b676-6f8fa10803b7.png)

I can bypass the error with `ignoreEmpty: true`

**Comment by rchl** [comment]
There is probably something about your git history that makes sentry-cli fail on it. It tries to find the history range from the last release to the specified commit. Maybe there is no previous release?

**Comment by madsh93** [comment]
Sorry! This was my own mistake. It seems my Github was not connected to Sentry. This article explains how to fix:

https://charles-stover.medium.com/how-i-debugged-sentry-release-no-commits-found-change-commits-range-d390ba4e326c
