### ISSUE TITLE
SENTRY_DSN when nuxt build --dotenv false

### ISSUE THREAD

**Issue by eclegend** [nuxt-community/sentry-module#370]
Hi, i got the problem with sentry reporting.

my .env 
```env
SENTRY_DSN: http://something...
```

my nuxt.config.js
```js
 sentry: {
    dsn: process.env.SENTRY_DSN_LOCAL || process.env.SENTRY_DSN || false,
  // ...
}
```

```
nuxt build --dotenv false && nuxt start --dotenv some_path
```

So, when i build without SENTRY_DSN and then start:

```
√ Sentry reporting is enabled (client side: enabled, server side: enabled)  
```
```json
{
 "nuxt": "^2.15.7",
 "@nuxtjs/sentry": "^5.1.5",
}
```

**Comment by rchl** [comment]
What result do you expect?

dsn is resolved at build time.

If you want it resolved at runtime, you could try using https://sentry.nuxtjs.org/sentry/runtime-config and overriding it with `sentry: { config: { dsn: '...' } }`.

**Comment by eclegend** [comment]
> What result do you expect?
> 
> dsn is resolved at build time.
> 
> If you want it resolved at runtime, you could try using https://sentry.nuxtjs.org/sentry/runtime-config and overriding it with `publicRuntimeConfig: { sentry: { config: { dsn: '...' } } }`.

What i do wrong?

```js
 sentry: {
   // dsn: 'some_dsn'
    config: {
      dsn: '',
       //...
    }
}
```

```js
publicRuntimeConfig: { sentry: { config: { dsn: 'process.env.SENTRY_DSN' } } }
```
```
$ nuxt build --dotenv false
i Sentry reporting is disabled (no DSN has been provided)     
```
```
$ nuxt start --dotenv ./config/.env
√ Sentry reporting is enabled (client side: enabled, server side: enabled)  
```

**Comment by rchl** [comment]
Try to provide DSN also during build (even if invalid).

Things are not fully runtime configurable so that workaround might be neede.

**Comment by eclegend** [comment]
@rchl thanks for your help!
This works:

sentry: { dsn: 'fake_dsn', config: {} }

publicRuntimeConfig: { sentry: { config: { dsn: 'process.env.SENTRY_DSN' } } }
