### ISSUE TITLE
Sentry performance transaction didn't captured from node

### ISSUE THREAD

**Issue by dzborowski** [nuxt-community/sentry-module#371]
Hi

When I'm trying to send sentry performance transaction on server side, transaction didn't showup in sentry preformance panel.
example https://github.com/dzborowski/nuxt-sentry-plugin

When I try to send same transaction using only @sentry/node package it's working correctly.
example https://github.com/dzborowski/nuxt-clear-sentry

In sentry project is created based on node I also tried vue but same result.
Same result in dev mode and also production build with NODE_ENV=production.
You can check transaction dispatch in plugins/sentry.server.js in both repos

**Comment by rchl** [comment]
In your plugin try getting sentry from `context.$sentry`.

The `process.sentry` is only meant to be used from within server middleware.

**Comment by dzborowski** [comment]
@rchl I switched to `context.$sentry` but also transaction didn't showup in sentry

**Comment by rchl** [comment]
And the log line on starting Nuxt says that Sentry is enabled on server?

**Comment by dzborowski** [comment]
yes
![Zrzut ekranu z 2021-11-22 12-04-51](https://user-images.githubusercontent.com/37987316/142850760-25aeb632-5aa0-40da-aead-2d86ca4776b6.png)

**Comment by dzborowski** [comment]
@rchl do you have an idea what could be wrong?

**Comment by rchl** [comment]
Not really. And I don't have a way to debug that since I don't have access to a plan with transactions.

**Comment by rchl** [comment]
You repos are gone. What was the Sentry module configuration that you were using?

**Comment by dzborowski** [comment]
@rchl I found soulution for my problem, tracesSampleRate option was only passed only to client, I need to pass it explicity to serverConfig(if I remember correctly), if it wasnt passed to server config tracing was disabled on server

**Comment by rchl** [comment]
This should be addressed in v6.0.0
