### ISSUE TITLE
Deprecated attachCommits actually still required

### ISSUE THREAD

**Issue by bmulholland** [nuxt-community/sentry-module#372]
[Docs say not to use `attachCommits`](https://sentry.nuxtjs.org/sentry/options#attachcommits) but[ the code only uses the replacement `publishRelease.setCommits` when `attachCommits` is set](https://github.com/nuxt-community/sentry-module/blob/607511a4e4c6000fbea78e811249839d4a1f7272/lib/core/hooks.js#L222).

**Comment by rchl** [comment]
`publishRelease` is initialized with the values provided through `options.publishRelease`:

https://github.com/nuxt-community/sentry-module/blob/607511a4e4c6000fbea78e811249839d4a1f7272/lib/core/hooks.js#L188

So when `publishRelease` is used we don't have to run that code you pointed to.

**Comment by bmulholland** [comment]
Well, okay, but then the documentation for publishRelease is wrong: https://sentry.nuxtjs.org/sentry/options#publishrelease

Specifically it says `setCommit.auto` defaults to true, but it does not because the code that defaults its value is inside the conditional I linked.

**Comment by bmulholland** [comment]
And actually, if I use the new `setCommit.auto` command, do I need to set repo myself, considering it's set when using `attachCommits`? https://github.com/nuxt-community/sentry-module/blob/607511a4e4c6000fbea78e811249839d4a1f7272/lib/core/hooks.js#L233

**Comment by rchl** [comment]
I'd say so, yes. PR welcome to update the example config.

**Comment by bmulholland** [comment]
Happy to contribute -- and thanks for all your help.

To be clear about what you're suggesting: update the docs to specify that `auto` is *not* set by default, and that repo should be set? FWIW, I gave it a try without repo set and it seems to be working fine -- so it may be sufficient to simply remove the mention that auto is true by default. Does that seem like the right change to you?

**Comment by rchl** [comment]
Yes, just removing the comment sounds good.
