### ISSUE TITLE
How to disable Pluggable Integrations?

### ISSUE THREAD

**Issue by ffarthbe** [nuxt-community/sentry-module#380]
- It seems that I can only change the config for the default integrations because of the function "merge" from 'lodash.mergewith'.
- Even if I write config like:
```
sentry: {
  clientIntegrations: {
    Dedupe: {},
  },
  serverIntegrations: {
    Dedupe: {},
  },
}
```
- Why I would like to do that?
Last week, after I upgraded sentry-module to v5.15, the integration "ExtraErrorData" cause recursive execution on server side.
It might be because the sentry event object has recursive references.
Eventually,ssr failed to render... Recursive execution fxxk cpu up...

![image](https://user-images.githubusercontent.com/38183711/145180760-858d488f-12cd-46b4-8989-313b3fceb537.png)

**Comment by rchl** [comment]
Have you tried if the issue reproduces with the latest version of this module? Coincidentally I had the same issue in my services and made a fix in this module that should mitigate it (at least it did in my case). See https://github.com/getsentry/sentry-javascript/issues/4186 for more details on the Sentry issue.

As for disabling integrations, you can do that by passing a `false` value.

```js
sentry: {
  clientIntegrations: {
    Dedupe: false,
  },
  serverIntegrations: {
    Dedupe: false,
  },
}
```

This should probably be documented.

**Comment by rchl** [comment]
BTW. I guess you meant `disable`, not `enable`, in the issue's title.

**Comment by ffarthbe** [comment]
@rchl Thank you for your reply and correction, I will try it with the latest version right away~

**Comment by rchl** [comment]
Also added documentation on disabling default integrations in #381
