### ISSUE TITLE
Upgrade @sentry/browser to 6.16.1 from 6.15.0.

### ISSUE THREAD

**Issue by joshwcorbett** [nuxt-community/sentry-module#382]
### Is your feature request related to a problem? Please describe.
Unrelated to any existing issues

### Describe the solution you'd like
Upgrade `@sentry/browser` to `6.16.1` from `6.15.0`

### Describe alternatives you've considered
Alternative workarounds not necessary

### Additional context
Other packages may need to updated in addition for proper functionality.

<details>
<summary>Sentry Dashboard Alert</summary>
<img width="741" alt="Screen Shot 2021-12-20 at 12 31 07 PM" src="https://user-images.githubusercontent.com/23065423/146822347-af0fa5eb-9015-4539-9d18-e4d981642886.png">
</details>

**Comment by rchl** [comment]
Running `npm upgrade @nuxtjs/sentry` should update the sub-dependencies of this package so there is no need for a new release really.

(At least with npm v7 or yarn. With npm v7 you can instead remove and re-install this package to get the same result.)
