### ISSUE TITLE
TypeError: this.$sentry.setUserContext is not a function

### ISSUE THREAD

**Issue by tanakaworld** [nuxt-community/sentry-module#40]
### Version

[v2.0.0 ](https://github.com/sentry-module/releases/tag/v2.0.0 )

### Reproduction link

[https://github.com/tanakaworld/nuxt-vue-error-handling-demo](https://github.com/tanakaworld/nuxt-vue-error-handling-demo)

### Steps to reproduce

Nuxt is v2.2.0.

1. Clone source code from reproduction link
2. Check out 'verify' branch
2. Setup according to README, and run 'npm run dev'
3. The error will happen at [here ](https://github.com/tanakaworld/nuxt-vue-error-handling-demoblob/verify/pages/index.vue#L34-L38)

![Screenshot 2018-11-11 00.06.08.png](https://cmty.s3.eu-west-1.amazonaws.com/107249265/2b9126d0-e4fa-11e8-9482-e37e1b6c7d81.png)

### What is expected ?

We can use a method 'this.$sentry.setUserContext'.

### What is actually happening?

We can use a method 'this.$sentry.setUserContext'.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sentry-module/issues/c33">#c33</a>)</em></sub></div>

**Comment by aldarund** [comment]
@tanakaworld there no setUserContext in new sentry SDK
See here
https://github.com/nuxt-community/sentry-module/issues/36#issuecomment-435723000
