### ISSUE TITLE
Does this work with the Node server in Nuxt.js?

### ISSUE THREAD

**Issue by patrickbjohnson** [nuxt-community/sentry-module#406]
We need to track errors on our API endpoints and we'd love to use this module as its already included for the client side. Aside from the `disable` based server side configurations there is no documentation that helps us understand/outline how to use this on the node/API side of Nuxt.js

**Comment by rchl** [comment]
It depends how you API is structured. It typically should work by default, if your API "trees" allow the errors to fallback to the Sentry's error handler. But if you are gonna add your own error handlers and terminate the "tree" then it won't fall back to to that.

**Comment by patrickbjohnson** [comment]
@rchl are there any docs pointing to this? Mostly what we're attempting to do is actually log specific errors from third party services within our API. As an example, we send transaction emails and on error of that service we want to log the error with sentry. 

However `this.$sentry` is not accessible but we can't find any documentation that would tell us otherwise.

**Comment by rchl** [comment]
On the API side you have `process.sentry`.

**Comment by patrickbjohnson** [comment]
thank you!!

Patrick Johnson
Progress Labs
@patrickbjohnson ( https://twitter.com/patrickbjohnson )
www.pbj.me ( http://www.pbj.me/ )

**Comment by patrickbjohnson** [comment]
Sorry to continue this thread but seems like `process.sentry` is not defined.Any ideas? Ultimately if there are documentation I can review happy to look at those!

**Comment by rchl** [comment]
You need to provide more info / code on what you are doing exactly.
