### ISSUE TITLE
file attachment for events

### ISSUE THREAD

**Issue by mjkhonline** [nuxt-community/sentry-module#410]
### Is your feature request related to a problem? Please describe.
I need to upload a log file when capturing an event. official vue plugin support this.
https://docs.sentry.io/platforms/javascript/guides/vue/enriching-events/attachments/

### Describe the solution you'd like
be able to attach a file.

**Comment by rchl** [comment]
You should be able to do it exactly like that documentation describes if you put that code in a custom client-side-only plugin.
