### ISSUE TITLE
"Discarded request mode session because autoSessionTracking option was disabled" warning while autoSessionTracking is enabled

### ISSUE THREAD

**Issue by mivd7** [nuxt-community/sentry-module#411]
Hi I'm having trouble capturing API request errors using Sentry for a project. I suspect it has to do with this warning that I'm getting when running the app: `Sentry Logger [warn]: Discarded request mode session because autoSessionTracking option was disabled`

It claims autoSessionTracking option was disabled. However I tried to enable it just about anywhere I could find in the docs, with this being my sentry config in nuxt.config.js:

```
sentry: {
    dsn: process.env.SENTRY_DSN_FRONTEND,
    publishRelease: {
      authToken: process.env.SENTRY_TOKEN,
      org: process.env.SENTRY_ORG,
      project: process.env.SENTRY_PROJECT
    },
    config: {
      debug: true,
      autoSessionTracking: true,
      environment: process.env.APP_ENV,
      release: `project-name@${process.env.APP_VERSION}`,
      sourceMapStyle: 'hidden-source-map',
      tracing: {
        tracesSampleRate: 0.02,
        vueOptions: {
          tracing: true,
          tracingOptions: {
            hooks: ['activate', 'mount', 'update'],
            timeout: 2000,
            trackComponents: true
          }
        }
      }
    },
    enableAutoSessionTracking: true,
    serverConfig: {
      autoSessionTracking: true
    },
    clientConfig: {
      autoSessionTracking: true
    }
  },
```

However I'm still getting the warning, and it doesn't report errors from requests. Why am I still getting this warning?

**Comment by rchl** [comment]
Is that a message from the server or client side?

Also, you can have a look at generated plugin file in `.nuxt/sentry.client.js` to see exactly with what settings the SDK is initialized (there is a line like `const config = ...`. Might help to see that.

**Comment by rchl** [comment]
Actually the generated #include `.nuxt/sentry.server.config.js` might be more relevant here as I think this is a server-side message.

**Comment by luispittagros** [comment]
I'm having the same issue.

**Comment by rchl** [comment]
If you still need help then please provide the information I've requested. Otherwise I can't do anything.
