### ISSUE TITLE
Access from plugin context clientside 

### ISSUE THREAD

**Issue by ThomasKientz** [nuxt-community/sentry-module#42]
I am trying to automatically track network errors.

```
export default function({ $axios, store, error, $raven }) {
  $axios.onError(e => {
    if (process.client) {
      $raven.captureException(e.response.data);
    }
    return Promise.reject(e);
  });
}
```

But `$raven` is undefined.

Any ideas ?

**Comment by aldarund** [comment]
1) there no $raven in latest version of nuxt sentry, its $sentry
2) export default function({ $axios, store, error, {app: { $sentry } }) {

**Comment by ThomasKientz** [comment]
@aldarund Thanks !

I was using v1 of sentry module using $raven. 

It doesn't work with :

`export default function({ $axios, store, error, app: { $sentry } }) {`

`$sentry` is still undefined.

It works though with :100: 

`export default function({ $axios, store, error, app }) {`

and then `app.$sentry`

**Comment by DiederikvandenB** [comment]
Could you maybe share some more code? In which file are you calling this code, what are you importing, etc.

**Comment by ThomasKientz** [comment]
@DiederikvandenB It's a simple nuxt plugin :

```
// plugins/axios.js
export default function({ $axios, store, error, app }) {
  $axios.onError(e => {
    if (process.client) {
      app.$sentry.configureScope(scope => {
        scope.setExtra("request", e);
        app.$sentry && app.$sentry.captureException(e.response.data);
      });
    }
    return Promise.reject(e);
  });
}
```

```
// nuxt.config.js
module.exports = {
  modules: [
    "@nuxtjs/axios",
  ],
  plugins: [
    "@/plugins/axios",
  ],
}

```

**Comment by seandelaney** [comment]
What was the solution?

I have a similar issue where `$sentry` is undefined within my plugin: https://cmty.app/nuxt/sentry-module/issues/c36

**Comment by ThomasKientz** [comment]
@seandelaney solution for me was (as you see in the thread) 

using 
> `app.$sentry`

with module updated to v2.

**Comment by ThomasKientz** [comment]
Ok I think I finally get it ! My guess :

Sentry is working in client side only, but the plugin **is not registered** for client side only cause I need it to be initiated in server side (as I need for axios)

But I am calling `$sentry` only in `$axios.onError(e => { ... app.$sentry })` through `app` and its working cause by the time `$sentry` had time to be injected !

**Comment by DiederikvandenB** [comment]
Sorry for not responding! Completely forgot. Very glad you were able to resolve it yourself.
