### ISSUE TITLE
Sourcemap uploaded to sentry but not reflecting to stack trace

### ISSUE THREAD

**Issue by mmestiyak** [nuxt-community/sentry-module#431]
Sourcemaps uploaded to sentry to see more realistic stack trace but it's not working, please help somebody

here's my config

```  sentry: {
    dsn: process.env.SENTRY_DSN,
    publishRelease: {
      include: [], // automatically set at publishing time to relevant paths for the bundles that were built
      ignore: [
        'node_modules',
        '.nuxt/dist/client/img'
      ],
      configFile: 'sentry.properties',
    },
    config: {
      release: 'release-1.0.0'
    },
    sourceMapStyle: 'hidden-source-map',
    disableServerSide: true,
    environment: 'development'
  }```

**Comment by mmestiyak** [comment]
![image](https://user-images.githubusercontent.com/50128043/177252377-ee309c44-c62e-441e-bf4a-0664bace2dca.png)
It's showing this kind of stack trace instead of showing real code

and files also uploaded to sentry
![image](https://user-images.githubusercontent.com/50128043/177252492-6843906a-33d5-4c90-bdbc-e77c9788e03f.png)

**Comment by rchl** [comment]
Try removing `sourceMapStyle` option and `include` from `publishRelease`.

**Comment by mmestiyak** [comment]
@rchl  Thank you so much for response, is this config okay now!

```
  sentry: {
    dsn: process.env.SENTRY_DSN,
    publishRelease: {
      include: [], // automatically set at publishing time to relevant paths for the bundles that were built
      ignore: [
        'node_modules',
        '.nuxt/dist/client/img'
      ],
      configFile: 'sentry.properties',
      sourceMapStyle: 'hidden-source-map',

    },
    config: {
      release: 'release-1.0.0'
    },
    disableServerSide: true,
    environment: 'development'
  }
 ```

**Comment by rchl** [comment]
Appears OK but you can remove `ignore` since you are just repeating what the module sets by default.

**Comment by mmestiyak** [comment]
@rchl  But it still doesn't show actual source code 😕

![image](https://user-images.githubusercontent.com/50128043/177281405-32370e06-9c52-4b41-9ff7-438662515c9b.png)

**Comment by rchl** [comment]
Not sure then.
- Does sentry show some error related to not being able to parse source maps in individual events?
- Does the artifact name start with a dash (`-`) in your case? I thought that it normally is tilde (`~`). Maybe your other Nuxt config settings affect it.

**Comment by mmestiyak** [comment]
Sentry is showing this one, but it's just because i didn't connect it with my github repo but i did write release version manually in config, in case my sentry is self-hosted it's running in docker.

![image](https://user-images.githubusercontent.com/50128043/177287859-1bcff8c5-70b4-42b8-b5e3-a32c746763a9.png)

**Comment by rchl** [comment]
I don't think I'll be able to help more with the given amount of information. You can potentially ask on Sentry's Discord for help.

**Comment by mmestiyak** [comment]
I already asked there while creating this

**Comment by rchl** [comment]
I'll close this now because we can't act on it without more information. We'll re-opened if more information is provided.

If it still doesn't work from you then please provide:
 - full log from "nuxt build" including the part that publishes the release
 - the request data from the network request that is sent to Sentry when capturing the error

(if there any sensitive information then you'd have to make sure to filter those out)
