### ISSUE TITLE
Upgrade to Sentry packages v7

### ISSUE THREAD

**Issue by bmulholland** [nuxt-community/sentry-module#433]
https://github.com/getsentry/sentry-javascript/releases/tag/7.0.0

**Comment by alexcroox** [comment]
Sentry blogged about the size reduction in v7, it would be great to have this updated so we can improve the perf of our Nuxt apps.

https://blog.sentry.io/2022/07/19/javascript-sdk-package-reduced/

@rchl is there a possibility of having Sentry as a peer dependancy so this module doesn't need to be re-published every time they make a release?

**Comment by rchl** [comment]
> @rchl is there a possibility of having Sentry as a peer dependancy so this module doesn't need to be re-published every time they make a release?

`npm` (and `yarn` too, pretty sure) will update the `@sentry/*` depenencies within specified range when running `npm update @nuxtjs/sentry` so there is not really a need to make those into peer dependencies.

**Comment by bmulholland** [comment]
The range specifies 6, so upgrading to 7 is not possible right now.

**Comment by rchl** [comment]
My answer was not in relation to updating to version 7 but only about upgrading to new patch/minor releases within the v6 range.

As far as upgrading to v7, this is a task on its own as it needs changes in the module and using peer dependencies wouldn't change anything in that regard.

**Comment by alexcroox** [comment]
good to know about running npm update for minor bumps, thanks

**Comment by iTechSebastianoLaini** [comment]
any ETA on this? @sentry/tracing it's blocked to V6 because @nuxtjs/sentry still used V6 and not 7.

**Comment by glebv** [comment]
Hi, our company is going to use sentry-module in production but it doesn't support v7 libs. sentry.io ui warns that our code uses old sdk. Could you share some estimates or insights about the migration? Should we expect on the soon migration? 
Thanks a lot for your work!

**Comment by rchl** [comment]
Not making any promises due to short on time.

Technically there should be no issues with using v6. We are doing that at my company and as long as it works fine it's not a priority to update.

**Comment by glebv** [comment]
@rchl thanks for your answer. Got it.

**Comment by vedmant** [comment]
I'm currently optimizing my nuxt app for google page speed tests and sentry code is quite a large piece of code. Upgrading to version 7 would be really helpful. Otherwise looks like I need to copy paste plugins and use sentry package directly.

**Comment by bmulholland** [comment]
@rchl Do you have time to post a short description of what would be needed to make the upgrade happen? That way, maybe someone for whom it's a higher priority could make an attempt.

**Comment by rchl** [comment]
The task would be to adapt the module so that it's compatible with the new SDK, paying attention to all breaking changes. Not much else to it, I think.

https://github.com/nuxt-community/sentry-module/issues/417 has some hints and even code to get this started.

**Comment by bmulholland** [comment]
@vedmant maybe doing that work would be less work overall than the plugin copying you are considering?
