### ISSUE TITLE
Sentry is making the web app freeze ⛔️

### ISSUE THREAD

**Issue by kubilaycaglayan** [nuxt-community/sentry-module#440]
### Version
@nuxtjs/sentry: ^5.1.7
nuxt: ^2.14.0

### Steps to reproduce

I can only share a log partial with you since we disabled the sentry to unfreeze our application.

![image](https://user-images.githubusercontent.com/60448833/186979238-e009c095-29ef-45fe-8e18-7dabb154f8d3.png)

This is what Google Chrome points out as an automatic debug point, just before the OOM crash.
This infinite loop is causing our application to freeze.

I know it can be very hard to understand what is the issue here from our limited source of information, but please, let me know if I can provide more information for you.

### What is Expected?

The sentry handles the error without freezing the application.

### What is actually happening?

Our web application is freezing _**most probably when sentry is trying to handle an error that we are having**_.

**Comment by rchl** [comment]
How does your Sentry configuration look like?

It sounds a lot like https://github.com/getsentry/sentry-javascript/issues/4186 which was both worked around in this module at some point and also addressed in Sentry SDK itself. Make sure that you have latest version of this module and SDK installed (`npm upgrade @nuxtjs/sentry` or `yarn upgrade @nuxtjs/sentry`). You don't need the v6 version of the module released today if you don't want to deal with breaking changes).

**Comment by kubilaycaglayan** [comment]
Hi @rchl 👋🏻 

Thanks for the quick response. Seems like we already have the latest.

1. It looks like this in `nuxt.config.js`

```JavaScript
sentry: {
  disabled: false,
  config: {
    environment: "production"
  },
  publishRelease: {
        org: "",
        project: "",
        cleanArtifacts: true,
        setCommits: {
          auto: false,
          repo: "",
          commit: "",
          ignoreMissing: true
        }
      }
  tracing: {
    tracesSampleRate: 0.1,
    vueOptions: {
      tracing: true,
      tracingOptions: {
        hooks: ["activate", "mount", "update"],
        timeout: 3000,
        trackComponents: false
      }
    },
    browserOptions: {}
  }
}
```

2. "@nuxtjs/sentry": "^5.1.7",
"@sentry/tracing": "^6.19.7",
"@sentry/webpack-plugin": "^1.18.9",

**Comment by rchl** [comment]
You could also try with:

```js
    sentry: {
        config: {
            normalizeDepth: 4,
        },
     }
```

or even lower value.

If it helps then it means that you have some strange error object that Sentry can't deal with property during serialization.

**Comment by kubilaycaglayan** [comment]
Thanks, @rchl 

It didn't help.
Since we have the updated version too, I think this leaves us with an error that we don't know how to solve.

How can we debug this? Do you have further ideas?

**Comment by rchl** [comment]
By adding `beforeSend` hook to the (server side) config you can log and inspect all exceptions that are being triggered.

If you can figure out which exceptions trigger the issue specifically, you can then make next steps like reporting an issue to Sentry or making sure that those exception objects are pre-processed by you first to not trigger the bug.

**Comment by kubilaycaglayan** [comment]
Thanks for the help, @rchl 

We found out the triggering internal issue. 

```JavaScript
Uncaught TypeError: Cannot read property 'value' of undefined
```

We solved our issue and it is not triggering the `sentry` bug anymore. 

But it is still a concerning `sentry` bug since it freezes the application. Is there any way that we can report it and make sure it'll be fixed in the future? So that other ppl won't experience such a time loss and a broken app.

**Comment by rchl** [comment]
You'd have to figure out reproduction steps and submit an issue.

It's also possible that it's already fixed in v7 of the SDK.

I've seen those issues being triggered when using services like DataDog and some other that track and enhance errors internally.
