### ISSUE TITLE
Nuxt 2.13 is the minimum required version

### ISSUE THREAD

**Issue by moltar** [nuxt-community/sentry-module#462]
### Version
@nuxtjs/sentry: 6.0.1
nuxt: 2.12.2

### Sentry configuration

N/A

### Reproduction Link

N/A

### Steps to reproduce

N/A

### What is Expected?

According to the docs Nuxt.js v2.4.0+ is required:

https://github.com/nuxt-community/sentry-module/blob/07fb5ced9ded01ac7ab72f7280d0e539812ad61f/docs/content/en/guide/setup.md?plain=1#L10

### What is actually happening?

`publicRuntimeConfig` was released in 2.13+

https://nuxtjs.org/tutorials/moving-from-nuxtjs-dotenv-to-runtime-config/#introducing-the-nuxt-runtime-config

**Comment by rchl** [comment]
I guess the two options here are:
a) update the documentation
b) gracefully handle Nuxt <2.13 without supporting runtime config
