### ISSUE TITLE
"Releases" page in docs is out-of-date

### ISSUE THREAD

**Issue by allanlewis** [nuxt-community/sentry-module#464]
### Version

n/a

### Sentry configuration

n/a

### Reproduction Link

https://sentry.nuxtjs.org/releases/

### Steps to reproduce

Go to the linked page.

### What is Expected?

The latest release listed should be 6.0.2, as per https://github.com/nuxt-community/sentry-module/releases

### What is actually happening?

The latest release listed is 6.0.0-beta.2.

**Comment by rchl** [comment]
Solved now with help of Nuxt team.

**Comment by allanlewis** [comment]
So you've dropped the "releases" page entirely? Shame it's too difficult to keep it up-to-date 😢 

Anyway, thanks for the quick response 🙏

**Comment by rchl** [comment]
That was not the intention. Fixed now.

**Comment by allanlewis** [comment]
> That was not the intention. Fixed now.

Thanks!
