### ISSUE TITLE
Prevent undefined this.$sentry while offline test

### ISSUE THREAD

**Issue by c4ss** [nuxt-community/sentry-module#47]
### What problem does this feature solve?

Currently this module will completely avoid creating `this.$sentry` when there is no DSN specified or the disabled option is flagged - this causes any `this.$sentry.xxx` functions to error and completely prevents offline debugging without sentry reporting.

For local testing no error reporting is necessary as the console log is accessible to us and will end up clogging issues being reporting from real users

### What does the proposed changes look like?

[`serverless-sentry-lib` achieves this by deleting the DSN and installing nonetheless](https://github.com/arabold/serverless-sentry-lib/blob/master/src/index.js#L84) (although this uses the deprecated `Raven` package).

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sentry-module/issues/c40">#c40</a>)</em></sub></div>

**Comment by DiederikvandenB** [comment]
Hi, thanks for reporting. Would you be willing to open a PR for this?

**Comment by DiederikvandenB** [comment]
Thanks! I have some other commits I need to merge in too. On my todo for tonight or tomorrow.
