### ISSUE TITLE
@sentry/vue dependency not found

### ISSUE THREAD

**Issue by Kelmatou** [nuxt-community/sentry-module#485]
### Version
@nuxtjs/sentry: 7.0.1
nuxt: 2.15.8

### Sentry configuration
```
{
    dsn: "<dsn>",
    disabled: isDevelopmentMode,
    config: {
      environment: process.env.ENV,
      release: process.env.npm_package_version,
      autoSessionTracking: false
    },
    publishRelease: isDevelopmentMode ? false : {
      authToken: process.env.SENTRY_AUTH_TOKEN,
      url: '<url>',
      org: '<org>',
      project: '<project>',
      release: process.env.npm_package_version,
      include: [`dist/`],
      ignore: ['node_modules']
    }
  }
```

### Steps to reproduce
npm run dev

### What is Expected?
it builds without errors

### What is actually happening?
there is 1 build error:

```
This dependency was not found:
* @sentry/vue in ./.nuxt/sentry.client.js
To install it, you can run: npm install --save @sentry/vue 
```

When I run `npm list @sentry/vue` I get:
```
└─┬ @nuxtjs/sentry@7.0.1
  └── @sentry/vue@7.29.0
```

**Comment by rchl** [comment]
I suppose you can work around by installing `@sentry/vue` explicitly in your project. Might also have to do the same with `@sentry/integrations` and `@sentry/tracing` (if using `tracing`).

**Comment by Kelmatou** [comment]
Yes, I tried and it works. But it's surprising that we all need to install @nuxtjs/sentry's dependencies, even though it's listed as a dependency of this package. Maybe it's normal but I'd be curious to understand why

**Comment by rchl** [comment]
It's not normal and I consider it something to be fixed.

It happens in some projects depending on how the package manager chooses to install the dependencies. If it hoists `@nuxtjs/sentry` dependencies to the root of `node_modules` (which should happen most of the time) then it works. Otherwise the client side can fail to resolve the dependencies.

**Comment by rchl** [comment]
Fixed in https://github.com/nuxt-community/sentry-module/releases/tag/v7.0.2.
You should no longer need to install `@sentry/*` dependencies manually.
