### ISSUE TITLE
Ability to set tracesSampleRate in runtime

### ISSUE THREAD

**Issue by romash1408** [nuxt-community/sentry-module#498]
### Is your feature request related to a problem? Please describe.
I need to set different sample rates for different environments
Also I want to be able to chenge it at any time without app rebuilding

### Describe the solution you'd like
Read `tracing` configuration from `publicRuntimeConfig`

**Comment by rchl** [comment]
Technically `tracing` object is just a syntactic sugar and it ends up setting values on the normal config.

So you should be able to override `tracesSampleRate` by setting `config.tracesSampleRate` in `publicRuntimeConfig`.

**Comment by romash1408** [comment]
@rchl thank you! Sorry that I didn't try it before ask question...
```js
publicRuntimeConfig: {
    sentry: {
        config: {
            tracesSampleRate: process.env.SENTRY_TRACING_SAMPLE_RATE,
        },
    },
},
```

**Comment by romash1408** [comment]
I hurried: looks like it works only on server side, but on client side I get this
![image](https://user-images.githubusercontent.com/14085271/219601265-f17d1148-eb5e-4810-b632-c5dc925ee312.png)
:(

**Comment by rchl** [comment]
I don't have time to test but I think this will fix it: https://github.com/nuxt-community/sentry-module/pull/499

It looks like the runtime config was applied before tracing options were merged so the latter overrode the former.

**Comment by romash1408** [comment]
Thank you very much for such a quik response, I checked you fix in my project, everything works now!
