### ISSUE TITLE
Redundant DSN required in configuration to initialize Sentry

### ISSUE THREAD

**Issue by vsetka** [nuxt-community/sentry-module#50]
### Version

[2.2.1](https://github.com/sentry-module/releases/tag/2.2.1)

### Reproduction link

[https://jsfiddle.net/dg37h4wa/](https://jsfiddle.net/dg37h4wa/)

### Steps to reproduce

Create a config in nuxt.config.js
```
{
  sentry: {
    dsn: 'my_dsn',
    config: {
      environment: 'staging'
    }
  }
}
```
Sentry will not initialize because it checks for both options.dsn AND options.config.dsn (https://github.com/nuxt-community/sentry-module/blob/master/lib/sentry.js#L26) so to make it work, we must add the dsn twice, like so:
```
{
  sentry: {
    dsn: 'some_dsn',
    config: {
      environment: 'staging',
      dsn: 'my_dsn'
    }
  }
}
```
### What is expected ?

Sentry is initialized when dsn is set in options

### What is actually happening?

Sentry gets initialized only when the dsn prop is set in the top level options AND the additional config options

### Additional comments?

Your issue reporting is very involved and cumbersome (why is reproduction required even in simple cases such as this one?). It deters from even reporting a bug. If you insist on such a model, at least make sure that everything works then. For example, fetching the version of this module doesn't work and it lists no versions for sentry-module (https://cmty.app/api/communities/nuxt/repos/sentry-module/releases/search)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sentry-module/issues/c42">#c42</a>)</em></sub></div>

**Comment by DiederikvandenB** [comment]
This is fixed in #52.

With regards to the issue reporting: it's not something I insist on using, but it's the default for any of the NuxtJS community repo's.
