### ISSUE TITLE
Setup release version

### ISSUE THREAD

**Issue by kolesoffac** [nuxt-community/sentry-module#505]
I use nuxt-module nuxt/sentry. I deploy release to Sentry self-hosted server.
How can i use human-version aka v1.0.1 for nodejs-part instead git hash?

I see code: https://github.com/nuxt-community/sentry-module/blob/main/lib/core/hooks.js#L158
So release version takes from sentry.release.config.js.
How create it:
https://github.com/nuxt-community/sentry-module/blob/main/lib/core/hooks.js#L39
and release takes from resolveRelease method.
But there just call propose version from sentry/cli: https://github.com/nuxt-community/sentry-module/blob/main/lib/core/options.js#L34

So i have question:
How can i use human-version aka v1.0.1 for nodejs-part instead git hash?

Thanks

**Comment by rchl** [comment]
You can define your own version in module config like:

```js
sentry: {
  config: {
    dsn: '...',
    release: 'my-project@1.1.1',
}
```

**Comment by kolesoffac** [comment]
It is runtime config. I want to it was part build in static code instead dynamic

**Comment by rchl** [comment]
You should be able to use runtime config to set it too and it should override what is set statically.

That said, if you also have `publishRelease` then you have to be aware that publishing released only happens on building so if you dynamically change version at runtime you might end up with a version that doesn't have related release and so resolving of source maps would work.

**Comment by kolesoffac** [comment]
I use publishRelease so i need to set version in code in build time. I can't define version dynamicly

**Comment by kolesoffac** [comment]
I already have it. But i have problem with set human-name release for application nodejs part in sentry.release.config.js after build process.

**Comment by rchl** [comment]
Slow your configuration

**Comment by kolesoffac** [comment]
{ 
   dsn,
    tracing: {
      tracesSampleRate: 1.0,
      vueOptions: {
        hooks: ['mount', 'update'],
        timeout: 2000,
        trackComponents: true
      },
      browserOptions: {}
    },
    config: {
      release: sentryRelease,
      environment: customEnv,
      autoSessionTracking: false
    },
publishRelease = {
        url: sentryUrl,
        org: sentryOrg,
        project: sentryProject,
        authToken: sentryAuthToken,
        release: sentryRelease,
        deploy: {
          env: customEnv
        },
        setCommits: {
          auto: true
        }
      }
}

When build time then variable sentryRelease is set, in runtime sentryRelease is not set.
For frontend part release set in static code, but for backend part don't set in sentry.release.config.js

**Comment by rchl** [comment]
Server side also merges runtime config at runtime: https://github.com/nuxt-community/sentry-module/blob/24d48719e3e2550941d2e664be25a4b5ace39c34/lib/core/options.js#L229-L229

Even without runtime config it should work for server side (but not client side) when just using module options since those are applied at runtime also.

Maybe your `sentryRelease` in `release: sentryRelease` is just not defined at runtime.

**Comment by kolesoffac** [comment]
sentryRelease is set, i get deploy in Sentry - https://docs.sentry.io/product/releases/

The release shouldn't be determined at runtime, it's build-level knowledge.

**Comment by rchl** [comment]
You need it set at runtime also so that the reported errors can be matched to releases created at build time...

**Comment by kolesoffac** [comment]
This is what we are talking about that this happens at the level of static code, which is obtained as a result of the build. And for the frontend this happens, but not for the backend, for the reason described in the first post. At the infrastructure level, when the application is launched, there is no information about the release, it must be embedded into the build itself.

In runtime i define just env name.

**Comment by rchl** [comment]
In my projects I just read name and version from `package.json` at runtime. But I see your point and it probably makes sense to created a snapshot of the version at build time for server side also.

**Comment by kolesoffac** [comment]
I build docker image and want to define release name inside

**Comment by kolesoffac** [comment]
Good.
Do you offer define in runtime on inside container from entrypoint?
