### ISSUE TITLE
SSR tracing won't working

### ISSUE THREAD

**Issue by arkhamvm** [nuxt-community/sentry-module#508]
What's wrong with my config?
SSR tracing won't working, so I separated DSN for easy debug.

### Version
@nuxtjs/sentry: 7.0.4
nuxt: 2.15.8

### Sentry configuration
```
  sentry: {
    dsn: true, // for canInitialize
    clientConfig: {
        dsn: process.env.SENTRY_CLIENT_DSN, // VueJS project
    },    
    serverConfig: {
      dsn: process.env.SENTRY_SERVER_DSN, // NodeJS project
      transport: makeNodeTransport,
    },
    lazy: false,
    disabled: false,
    tracing: {
      tracesSampleRate: 1.0,
      vueOptions: {
        tracing: true,
        tracingOptions: {
          hooks: ['mount', 'update'],
          timeout: 2000,
          trackComponents: true
        }
      },
      browserOptions: {}
    },
    config: {
      environment: 'codesandbox',
    },
  }
```  

### Reproduction Link
https://codesandbox.io/p/sandbox/elated-borg-9im5b7?file=%2Fnuxt.config.ts&selection=%5B%7B%22endColumn%22%3A17%2C%22endLineNumber%22%3A73%2C%22startColumn%22%3A17%2C%22startLineNumber%22%3A73%7D%5D

(I can provide access for trial sentry projects if needed)

### Steps to reproduce
Load page, then move to `about` page

### What is Expected?
Both client and server tracing is collected

### What is actually happening?
Only client tracing is collected

![image](https://user-images.githubusercontent.com/9816112/221535094-8192cced-183d-4766-be63-b0cbdb658063.png)
![image](https://user-images.githubusercontent.com/9816112/221535180-0cb18a61-8c52-4fb1-b06e-a63530106672.png)

**Comment by arkhamvm** [comment]
@rchl thanks!

**Comment by arkhamvm** [comment]
@rchl I updated sanbox to `@nuxtjs/sentry` `7.1.2`, but NodeJS transactions is still emty. What I'm doing wrong?

**Comment by rchl** [comment]
Probably you are doing something wrong but I'm not a mind reader.

Looking at your config in the initial comment, the `tracing` option is a root module option and you haven't set it.

**Comment by rchl** [comment]
Share updated project.

**Comment by arkhamvm** [comment]
> Share updated project.

Shoud be same link as above: 
https://codesandbox.io/p/sandbox/sharp-fire-4nvcxi?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A31%2C%22endLineNumber%22%3A17%2C%22startColumn%22%3A31%2C%22startLineNumber%22%3A17%7D%5D

**Comment by rchl** [comment]
How can I download this thing? Don't see any option to do that.

**Comment by rchl** [comment]
BTW. Why do you use different DSNs for server and client?

**Comment by arkhamvm** [comment]
> How can I download this thing? Don't see any option to do that.

Hmmm, looks like download option is deleted...
![image](https://user-images.githubusercontent.com/9816112/223360652-077cbee3-3b8d-48eb-ab72-815957faec0c.png)


> BTW. Why do you use different DSNs for server and client?

To separate tracings/errors, to be sure that is backend (NodeJS) trace.

**Comment by arkhamvm** [comment]
> How can I download this thing? Don't see any option to do that.

I moved it to github repo: 
https://github.com/arkhamvm/sharp-fire-4nvcxi

**Comment by arkhamvm** [comment]
> To separate tracings/errors, to be sure that is backend (NodeJS) trace.

BTW, for Relay in production

**Comment by rchl** [comment]
Works for me (I've removed `spa` mode setting):

![Screenshot 2023-03-07 at 09 15 03](https://user-images.githubusercontent.com/153197/223363377-c7d6d2e1-3516-43da-96f0-315083b8bbce.png)

**Comment by rchl** [comment]
Well, to be fair it appears to be showing same data as the Frontend and I can't quite see any Backend-specific data.

I haven't properly used this feature myself so not sure what to expect really.

**Comment by rchl** [comment]
Fixing in https://github.com/nuxt-community/sentry-module/pull/517

Note that you config has some invalid values (or in wrong places). It can be simplified to:

```js
  sentry: {
    dsn: true, // for canInitialize
    clientConfig: {
      dsn:
        '...',
    },
    serverConfig: {
      dsn:
        '...',
    },
    lazy: false,
    disabled: false,
    tracing: {
      tracesSampleRate: 1.0,
    },
    config: {
      environment: 'codesandbox',
      debug: true,
    },
  },
```

**Comment by rchl** [comment]
> I'm trying to find backend/SSR bottle-necks (slow render components, slow api's e.t.c.)

I don't think server tracing will give you that kind of information. That sounds more like profiling which is a separate feature - https://docs.sentry.io/platforms/node/profiling/

**Comment by arkhamvm** [comment]
> EDIT: although even with profiling you will probably not have that good visibility into the components.

@rchl I need to pass `profilesSampleRate` too, right? Where it should be? In `serverConfig`, `config` or `tracing`?

**Comment by rchl** [comment]
`config` should be fine.
You also have to add the profiling integration using `customServerIntegrations`.

**Comment by arkhamvm** [comment]
> `config` should be fine. You also have to add the profiling integration using `customServerIntegrations`.

Thanks!

**Comment by arkhamvm** [comment]
@rchl You are right, even outgoing http requests doesn't captured by default. 
But, Nuxt2 is packed with `axios` maybe add this interceptors by default?

```
// ~/plugins/axios.js
export default function({ app, $axios, redirect, res, error }) {
	$axios.onRequest((config) => {
		if (process.server) {
			const hub   = require('@sentry/node').getCurrentHub();
			const span  = hub.getScope().getTransaction().startChild({
				op:          'http.' + config.method,
				description: config.url,
			});

			config.metadata = {
				sentrySpan: span,
			};

			// `sentry-trace` header, etc
			for (const [key, value] of Object.entries(hub.traceHeaders())) {
				config.headers[key] = value;
			}
		}
	});

	$axios.onRequestError((axiosErr) => {
		if (process.server && axiosErr?.config?.metadata) {
			if (axiosErr.config.metadata.sentrySpan) {
				axiosErr.config.metadata.sentrySpan.setStatus('unknown_error');
				axiosErr.config.metadata.sentrySpan.finish();
			}
		}
	});

	$axios.onResponse((response) => {
		if (process.server && response?.config?.metadata) {
			if (response.config.metadata.sentrySpan) {
				response.config.metadata.sentrySpan.setStatus('ok');
				response.config.metadata.sentrySpan.setTag('http.status_code', response.status);
				response.config.metadata.sentrySpan.finish();
			}
		}
	});

	$axios.onResponseError((axiosErr) => {
		if (process.server && axiosErr?.config?.metadata) {
			if (axiosErr.config.metadata.sentrySpan) {
				axiosErr.config.metadata.sentrySpan.setStatus('ok');
				axiosErr.config.metadata.sentrySpan.setTag('http.status_code', axiosErr.status);
				axiosErr.config.metadata.sentrySpan.finish();
			}
		}
	});

	$axios.onError((axiosErr) => {
		if ($axios.isCancel(axiosErr)) {
			if (process.server && axiosErr?.config?.metadata) {
				if (axiosErr.config.metadata.sentrySpan) {
					axiosErr.config.metadata.sentrySpan.setStatus('cancelled');
					axiosErr.config.metadata.sentrySpan.finish();
				}
			}

			return;
		}

		if (process.server && axiosErr?.config?.metadata) {
			if (axiosErr.config.metadata.sentrySpan) {
				axiosErr.config.metadata.sentrySpan.setStatus('unknown_error');
				axiosErr.config.metadata.sentrySpan.setTag('http.status_code', axiosErr.status);
				axiosErr.config.metadata.sentrySpan.finish();
			}
		}
	});
}
```

**Comment by rchl** [comment]
Nuxt 2 doesn't come with axios.

But maybe it it still makes sense to include an optional plugin like that. Though I'm afraid that it would be to restrictive. It's probably better to document this instead and let user manually handle it.
