### ISSUE TITLE
disabled option does not work

### ISSUE THREAD

**Issue by tic40** [nuxt-community/sentry-module#51]
### Version

[v2.2.1](https://github.com/sentry-module/releases/tag/v2.2.1)

### Reproduction link

[https://jsfiddle.net/y5sa4ht8/](https://jsfiddle.net/y5sa4ht8/)

### Steps to reproduce

Set the following sentry config in nuxt.config.js.

```
{
  sentry: {
    dsn: 'dsn',
    disabled: true,
    config: {
      environment: process.env.NODE_ENV // 'development'
    }
  }
}
```

### What is expected ?

I expect that sentry-module does not send error reports because disabled option is true.

### What is actually happening?

Though I set `disabled: true`, sentry-module sends error reports.

### Additional comments?

This works well on v2.1.0. I met this on v2.2.1.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sentry-module/issues/c43">#c43</a>)</em></sub></div>

**Comment by DiederikvandenB** [comment]
See #53
