### ISSUE TITLE
context.$sentry is undefined in nuxt plugins when disabled in 7.1.11

### ISSUE THREAD

**Issue by meinenieuwland** [nuxt-community/sentry-module#553]
### Version
@nuxtjs/sentry: 7.1.11
nuxt: 2.15.8

### Sentry configuration
```js
sentry: {
    disabled: !logSentryErrors,
    dsn: process.env.SENTRY_DSN,
    publishRelease: {
      authToken: process.env.SENTRY_AUTH_TOKEN,
      org: process.env.SENTRY_ORG,
      project: process.env.SENTRY_PROJECT,
      setCommits: {
        auto: true,
      },
    },
    config: {
      ignoreErrors: sentryIgnoredErrors,
      release: `${process.env.SENTRY_PROJECT}@${packageJson.version}`,
    },
    clientConfig: {
      replaysOnErrorSampleRate: parseFloat(process.env.SENTRY_ERROR_SESSION_SAMPLE_RATE),
      replaysSessionSampleRate: parseFloat(process.env.SENTRY_SESSION_SAMPLE_RATE),
    },
    customClientIntegrations: '~/plugins/init-custom-sentry-integrations.js',
  },
```

### Reproduction Link
-

### Steps to reproduce
-

### What is Expected?
`context.$sentry` should be available inside Nuxt plugins, when the Sentry "disabled" configuration option is `true`.

### What is actually happening?
Locally we set `logSentryErrors` to `false`. Before 7.1.11 `context.$sentry` was available inside nuxt plugins. But you would get this warning:
![image](https://user-images.githubusercontent.com/3862658/230389968-5abaf26a-81d4-4d74-a04d-1d381239e276.png)

As of 7.1.11 this isn't the case anymore. `context.$sentry` is `undefined`.

**Comment by rchl** [comment]
I can't quite reproduce this, to be honest.
How do the generated `.nuxt/sentry.client.js` and `.nuxt/sentry.server.js` files look like for you?

**Comment by meinenieuwland** [comment]
I've tested this again today. And I can't reproduce it. I'm sorry to have wasted you time then 😞
