### ISSUE TITLE
"Errors will not be logged" log doesn't indicate where it's coming from

### ISSUE THREAD

**Issue by rchl** [nuxt-community/sentry-module#56]
### What problem does this feature solve?

The Errors will not be logged because the disable option has been set console log that triggers on starting nuxt app doesn't indicate what module it's coming from so it looks like it's a message triggered by nuxt itself. I think it would be nice to indicate that it's sentry module saying that.

### What does the proposed changes look like?

Prefix strings (two instances) with [sentry-module] maybe.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sentry-module/issues/c45">#c45</a>)</em></sub></div>

**Comment by DiederikvandenB** [comment]
Thank you for your question. I could not reproduce your issue. These are the steps I took:

``` bash
$ npx create-nuxt-app nuxt-sentry-test
$ cd nuxt-sentry-test
$ yarn add @nuxtjs/sentry
# add the sentry module to your nuxt.config.js
$ yarn run dev
```

And then this is my output:
``` bash
yarn run v1.13.0
$ nuxt
ℹ Errors will not be logged because no DSN has been provided                   nuxt:sentry 13:55:41
ℹ Preparing project for development                                                        13:55:43
ℹ Initial build may take a while                                                           13:55:43
✔ Builder initialized                                                                      13:55:43
✔ Nuxt files generated                                                                     13:55:43
```

As you can see, the `nuxt:sentry` namespace is added to the first line, on the right hand side. Let me know if the issue persists when you follow these steps.

**Comment by rchl** [comment]
That's true, my screen is too wide for me to notice it there on the other side. :)
I think it's not ideal way of displaying source of message but it's not a problem of this module itself.

**Comment by DiederikvandenB** [comment]
I agree with you there, it's not ideal for wider screens.

Earlier on actually, we used to do logging like you proposed, as you can see here:
https://github.com/nuxt-community/sentry-module/commit/f6abcc830c1690203479460feadba52b2ef6dee7

However, to comply with Nuxt v2.0 we moved to Consola too. I would recommend opening an issue in either of those repository's if you want to have the original problem fixed. Good luck!
