### ISSUE TITLE
serverConfig doesn't replace dsn

### ISSUE THREAD

**Issue by arkhamvm** [nuxt-community/sentry-module#567]
### Version
@nuxtjs/sentry: 7.2.4
nuxt: 2.15.8

### Sentry configuration
```
  modules: [
    '@nuxtjs/axios',
    ['@nuxtjs/sentry', { ignore: ['node_modules'] }],
  ],
```

```
  sentry: {
    dsn: 'vue_dsn', 
    serverConfig: {
      dsn: 'node_dsn',
    },
    lazy: false,
    disabled: false,
    debug: true,
    tracing: {
      tracesSampleRate: 1.0,
    },
    config: {
      environment: 'codesandbox',
    },
  },
```

### Reproduction Link
https://codesandbox.io/p/sandbox/zealous-blackburn-00w1y6?file=%2Fpages%2Fabout%2Findex.vue%3A28%2C4

### Steps to reproduce
Open `about` page

### What is Expected?
Server Error sended to `dsn` from `serverConfig`

### What is actually happening?
Server Error sended to default `dsn`

![image](https://github.com/nuxt-community/sentry-module/assets/9816112/8e65a17a-4de3-432d-8abe-f6bda1ee67d0)

![image](https://github.com/nuxt-community/sentry-module/assets/9816112/ee1fef97-8d5a-415b-a674-d3a25cfd821e)

**Comment by rchl** [comment]
Good catch. The logic of merging default/user/server config was backwards that resulted in the global `dsn` having priority. Fixed in #568.

**Comment by rchl** [comment]
BTW. The `ignore` setting doesn't apply where you've put it. It's part of the `publishRelease` object and defaults to:

```
      ignore: [
        'node_modules',
        '.nuxt/dist/client/img',
      ],
```

already so maybe you shouldn't even override it.

**Comment by arkhamvm** [comment]
@rchl Can you also check perfomance tracing? Looks like it's same issue.

https://codesandbox.io/p/sandbox/hopeful-knuth-bou0pb?file=%2Fpages%2Fabout%2Findex.vue%3A15%2C42

VueJS tracing is OK:
![image](https://github.com/nuxt-community/sentry-module/assets/9816112/e6785021-1b2f-4f0b-a894-41b8d6c1a888)

NodeJS tracing not working:
![image](https://github.com/nuxt-community/sentry-module/assets/9816112/7465a3ed-7328-4a8d-b42a-7ee52ab4c8fd)

**Comment by rchl** [comment]
Can you apply this patch in `node_modules/@nuxtjs/sentry/dist/module.mjs` and see what is printed on starting Nuxt? It should tell you exactly what config is used and whether it's a config issue.

```diff
--- /node_modules/@nuxtjs/sentry/dist/module.mjs	Wed May 10 14:45:01 2023
+++ /node_modules/@nuxtjs/sentry/dist/module.mjs	Fri May 19 09:07:12 2023
@@ -532,6 +532,7 @@
   const config = defu({ release }, serverOptions.config);
   process.sentry = Sentry;
   if (canInitialize(moduleOptions)) {
+    console.info({config})
     Sentry.init(config);
     sentryHandlerProxy.errorHandler = Sentry.Handlers.errorHandler();
     sentryHandlerProxy.requestHandler = Sentry.Handlers.requestHandler(moduleOptions.requestHandlerConfig);
```

**Comment by arkhamvm** [comment]
prod build
```
$ npm run build
✔ Sentry reporting is enabled (client side: enabled, server side: enabled)
ℹ Production build
ℹ Bundling for server and client side
ℹ Target: server
✔ Builder initialized
✔ Nuxt files generated   

sentry_config {                                                                                                                
  config: {
    dsn: 'SERVER_DSN',
    integrations: [
      [Http],
      [Dedupe],
      [ExtraErrorData],
      [RewriteFrames],
      [Transaction]
    ],
    environment: 'production',
    tracesSampleRate: 1,
  }
}
```

dev watch
```
$ npm run dev

✔ Sentry reporting is enabled (client side: enabled, server side: enabled)    
ℹ Preparing project for development
ℹ Initial build may take a while
✔ Builder initialized
✔ Nuxt files generated

sentry_config {
  config: {
    dsn: 'SERVER_DSN',
    integrations: [
      [Dedupe],
      [ExtraErrorData],
      [RewriteFrames],
      [Transaction]
    ],
    environment: 'dev'
  }
}

```

**Comment by rchl** [comment]
Off... this needs a proper look. :)

BTW. `ignoreErrors` is in a wrong place. Should be in config/clientConfig/serverConfig.
