### ISSUE TITLE
Version 2.7.5 breaks in nuxt 2.16.3

### ISSUE THREAD

**Issue by fabiiomiiguel** [nuxt-community/sentry-module#570]
### Version
@nuxtjs/sentry: 7.2.5 
nuxt: 2.16.3 

### Sentry configuration
<!--
    If relevant, please include the configuration you are using for this module.
```
-->

### Reproduction Link
<!--
    A minimal test case on codesandbox or in a repository that can be used to reproduce the bug.
-->
```
 Nuxt instance is unavailable!

  at useNuxt (node_modules/@nuxtjs/sentry/dist/module.mjs:18:11)
  at getOptions (node_modules/@nuxtjs/sentry/dist/module.mjs:47:18)
  at ModuleContainer.normalizedModule (node_modules/@nuxtjs/sentry/dist/module.mjs:64:28)
  at node_modules/@nuxtjs/sentry/dist/module.cjs:2:53
  at async ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:167:20)
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:36:5)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:342:5)

   ╭──────────────────────────────────────────╮
   │                                          │
   │   ✖ Nuxt Fatal Error                     │
   │                                          │
   │   Error: Nuxt instance is unavailable!   │
   │                                          │
   ╰──────────────────────────────────────────╯
```

### Steps to reproduce

Upgrade from 7.2.3 for 7.2.5 and run `npm run dev`.

### What is Expected?

Run without break like in the previous version.

### What is actually happening?

Breaking the development mode.

**Comment by rchl** [comment]
Do you have nuxt kit in your project? `npm why @nuxt/kit`?

**Comment by rchl** [comment]
I don't know how to reproduce but I have a hunch what it could be caused by. I've made potential fix in https://github.com/nuxt-community/sentry-module/pull/571

You could try to apply this change manually to `node_modules/@nuxtjs/sentry/dist/module.mjs` and see if it helps.

**Comment by fabiiomiiguel** [comment]
Yes that fix works! Thank you!
