### ISSUE TITLE
build is failing: Cannot read properties of undefined (reading 'nuxt')

### ISSUE THREAD

**Issue by simonmaass** [nuxt-community/sentry-module#612]
### Version
@nuxtjs/sentry: 7.4
Nuxt 3.6.5 with Nitro 2.6.0

### Sentry configuration
default config

### Steps to reproduce
run yarn build

### What is Expected?
build works

### What is actually happening?

<html>
<body>

[error] Cannot read properties of undefined (reading 'nuxt')
--
14:23:06.770 | at normalizedModule (node_modules/@nuxtjs/sentry/dist/module.mjs:56:23)
14:23:06.770 | at installModule (node_modules/@nuxt/kit/dist/index.mjs:2409:101)
14:23:06.770 | at async initNuxt (node_modules/nuxt/dist/index.mjs:3238:7)
14:23:06.770 | at async loadNuxt (node_modules/nuxt/dist/index.mjs:3314:5)
14:23:06.770 | at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2537:19)
14:23:06.770 | at async Object.invoke (node_modules/nuxi/dist/chunks/build.mjs:38:18)
14:23:06.771 | at async _main (node_modules/nuxi/dist/cli.mjs:49:20)

</body>
</html>

<img width="641" alt="image" src="https://github.com/nuxt-community/sentry-module/assets/32599710/8f1d517a-f238-4092-847d-ba94f3cdc91f">

**Comment by kilab** [comment]
The same problem here :(


I tried to install previous versions, to 7.1, but neither version works. Nuxt 3.6.5 with Nitro 2.5.2

**Comment by rchl** [comment]
This module doesn't support Nuxt 3 currently. See #530
