### ISSUE TITLE
About Client or Server logging

### ISSUE THREAD

**Issue by benoitemile** [nuxt-community/sentry-module#63]
### What problem does this feature solve?

We would be able to have specific monitoring and alerting on client side errors differently from server side errors.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sentry-module/issues/c46">#c46</a>)</em></sub></div>

**Comment by aldarund** [comment]
closed in #72

**Comment by benoitemile** [comment]
thanks !!
