### ISSUE TITLE
add typescript defintions for $sentry

### ISSUE THREAD

**Issue by GexxOn** [nuxt-community/sentry-module#66]
right now $sentry is not available in the context or in a component. To solve this a proper typescript defintion is needed, right now to workaround this issue you simple can do:
1.) create a new "index.d.ts" file
2.) paste:
```
declare module 'vue/types/vue' {
    interface Vue {
        $sentry: any;
}
}
```
see also // https://vuejs.org/v2/guide/typescript.html#Augmenting-Types-for-Use-with-Plugins

but the correct solution would be not using "any", but the correct type. I tried it with:
import { NodeClient } from '@sentry/node';

but this collides with some other things, and actually it would be wrong on the client side too.

Could be the right way to provide a "unified" interface for both client&server and wrap the actual sentry calls behind it?

Regards
Gexxxn 3000

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sentry-module/issues/c50">#c50</a>)</em></sub></div>

**Comment by GexxOn** [comment]
ping @DiederikvandenB can you please reopen this issue? thanks

**Comment by simllll** [comment]
ping @manniL

**Comment by simllll** [comment]
ping @benoitemile  can you help?

**Comment by simllll** [comment]
re opened here https://github.com/nuxt-community/sentry-module/issues/67
