### ISSUE TITLE
Sentry is always disabled. What am I doing wrong?

### ISSUE THREAD

**Issue by sinneren** [nuxt-community/sentry-module#674]
Hello.
I tried to call captureException, but get message:
`$sentry.captureException() called, but Sentry plugin is disabled...`

Already tried different major versions of module: 7 & 8.
Tried to set disabled option manually, but still got message and nothing in panel.

```
"@nuxtjs/sentry": "8.0.6"
"@nuxtjs/composition-api": "^0.33.1",
"dotenv": "^16.4.5",
"@sentry/webpack-plugin": "^2.16.0",
"nuxt": "2.17.0",
```

Config:
```
publicRuntimeConfig: {
sentry: {
      dsn: process.env.SENTRY_DSN,
      config: {
        environment: process.env.SENTRY_ENVIRONMENT,
        denyUrls: [
          // Chrome extensions
          /extensions\//i,
          /^chrome:\/\//i,
          /metrics\.itunes\.apple\.com\.edgesuite\.net\//i,
          /google\.com\//i,
        ],
      },
    },
 }
```

nuxt2 with composition api, eg:

```
export default defineComponent({
  ...
  setup() {
    const { $sentry } = useContext();
    ....
    $sentry.captureException(name, err); // some call in client side
  }
})
```

**Comment by rchl** [comment]
From the [documentation](https://sentry.nuxtjs.org/configuration/runtime-config):

> Currently, only the config, clientConfig and serverConfig [options](https://sentry.nuxtjs.org/configuration/options) can be configured using the runtime config.
