### ISSUE TITLE
Support sever side integration

### ISSUE THREAD

**Issue by pi0** [nuxt-community/sentry-module#68]
### What problem does this feature solve?

Node integration and allow using `$sentry` in server side code

Related issues: #19, #33
Related PRs: #61

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sentry-module/issues/c52">#c52</a>)</em></sub></div>

**Comment by rchl** [comment]
I think you meant `$sentry` rather than `$dsn`.
With latest changes dsn is set properly so sentry catches errors properly on the server side. Just that `$sentry` object is not exposed.

**Comment by pi0** [comment]
Hi. Yes it was a after midnight typo 😂

**Comment by aldarund** [comment]
closed in #72
