### ISSUE TITLE
Sentry undefined in nuxtServerInit

### ISSUE THREAD

**Issue by felixdenoix** [nuxt-community/sentry-module#76]
### Version

[2.3.2](https://github.com/sentry-module/releases/tag/2.3.2)

### Reproduction link

[https://codesandbox.io/s/zwnoxjj21p?fontsize=14](https://codesandbox.io/s/zwnoxjj21p?fontsize=14)

### Steps to reproduce

Install module 
Setup module
Access sentry in the `nuxtServerInit` function from the store returns undefined. 

```javascript
  nuxtServerInit({ commit }, ctx) {
    console.log("HI SENTRY", ctx.$sentry); // here $sentry is undefined
  }
```

### What is expected ?

Being able to access the `$sentry` object in the nuxtServerinit method from the store.

### What is actually happening?

object does not exist in context 

### Additional comments?

I had a look to the different issues ( [#19](https://github.com/nuxt-community/sentry-module/issues/19), [#33](https://github.com/nuxt-community/sentry-module/issues/33) ), and releases ( [#72](https://github.com/nuxt-community/sentry-module/pull/72) ) but I still cannot access the sentry methods (also sorry in advance if I'm using the module the wrong way).
Thanks for this module it really made my day on multiple occasions !

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sentry-module/issues/c56">#c56</a>)</em></sub></div>

**Comment by rchl** [comment]
v2 does not expose sentry object on server side. v3 will but it's not yet released.

**Comment by felixdenoix** [comment]
Allright ! I thought the V3 flag was for meant for the 2.3 release :)
Apologies for the false bug report, would you know is there a planned date for the v3 ?
