### ISSUE TITLE
Ability to delete sourcemaps after uploading to sentry

### ISSUE THREAD

**Issue by mauxtin** [nuxt-community/sentry-module#77]
### What problem does this feature solve?

It would be useful to have an option to automatically delete the sourcemaps after they have been uploaded to sentry.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sentry-module/issues/c57">#c57</a>)</em></sub></div>

**Comment by matthieusieben** [comment]
```json

"scripts": {
  ...
  "build": "nuxt build && rimraf .nuxt/dist/**/*.js.map"
}
```
