### ISSUE TITLE
FATAL  Could not compile template - sentry.client.js: Unexpected token if

### ISSUE THREAD

**Issue by Jolg42** [nuxt-community/sentry-module#81]
### Version

[master](https://github.com/sentry-module/releases/tag/master)

### Reproduction link

[https://cmty.app/SorryIDontHaveOne](https://cmty.app/SorryIDontHaveOne)

### Steps to reproduce

Node.js 10.7.0
"nuxt": "2.6.3"
"@nuxtjs/sentry": "git://github.com/nuxt-community/sentry-module.git"

Deploying on Zeit Now v1 produce an error see "What is actually happening?"

### What is expected ?

A successful build

### What is actually happening?

```
> npm run build
> nuxt:sentry 13:58:09 ✔ Started logging errors to Sentry
> 13:58:10 ℹ Production build
> 13:58:10  FATAL  Could not compile template /home/nowuser/src/node_modules/@nuxtjs/sentry/lib/sentry.client.js: Unexpected token if
>   at Promise.all.templateFiles.map (node_modules/@nuxt/builder/dist/builder.js:5959:17)
>    ╰──────────────────────────────────────────��─────────────────────────────────────────╯
```

### Additional comments?

It could be related to merging https://github.com/nuxt-community/sentry-module/pull/75 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sentry-module/issues/c58">#c58</a>)</em></sub></div>

**Comment by pi0** [comment]
@Jolg42 Will fix it in short. BTW consider using specific git commits when using git dependency.

**Comment by Jolg42** [comment]
@pi0 Awesome thank you! And yes indeed, I only did that because I was doing a quick test to check if the new version solved my issue https://github.com/getsentry/sentry-javascript/issues/2052
Next time I'll add a ref so it's easier for you as well!

**Comment by pi0** [comment]
@Jolg42 should be fixed on master. I've also made tests working again. Good luck :)
