### ISSUE TITLE
Update Sentry SDK

### ISSUE THREAD

**Issue by eyalhakim** [nuxt-community/sentry-module#89]
### What problem does this feature solve?

![Screen Shot 2019-07-07 at 9.50.53 PM.png](https://cmty.s3.eu-west-1.amazonaws.com/107249265/e65c1070-a0ec-11e9-99b6-ffeb75e0a855.png)

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sentry-module/issues/c64">#c64</a>)</em></sub></div>

**Comment by rchl** [comment]
Dependencies are not pinned so if you uninstall and install this module again, you'll get latest SDK version. (There might also be command for that in yarn but AFAIK not in npm).

(But maybe dependencies should be pinned and handled by renovate bot. As long as package maintenance and releases would be swift, it would probably be easier than having to manually update sub dependencies. @aldarund)

**Comment by eyalhakim** [comment]
Makes sense that they should be pinned to prevent breaking changes from breaking the library.

**Comment by rchl** [comment]
There are pros and cons in both approaches.

Current approach's upside is that you can update Sentry without depending on new nuxt sentry module release. And as long as you are using lock file, sentry dependency will not update on itself. And even if it would, it would be within same major version so it shouldn't break anything (assuming that Sentry developers don't make mistake of releasing breaking changes in minor release which I think they won't).

Current approach's downside is that it's actually a bit tricky to update Sentry dependency if you really want to do it.

**Comment by aldarund** [comment]
closing, updated deps to latest in 3.0.1
