### ISSUE TITLE
NuxtJS 1.0.0 errorMiddleware undefined

### ISSUE THREAD

**Issue by steffen1249** [nuxt-community/sentry-module#9]
At Nuxt release 1.0.0 they did braking changes to their hook system which included a rewrite of how they use their errorMiddleware.

The errorMiddleware is no longer a part of the Renderer class, which results in errorMiddleware being undefined and the custom sentry middleware is not called at any point because of this.

Please refer to how it was done prior to the release here:
[https://github.com/nuxt/nuxt.js/blob/v1.0.0-rc11/lib/core/renderer.js#L323](https://github.com/nuxt/nuxt.js/blob/v1.0.0-rc11/lib/core/renderer.js#L323)

And after 1.0.0 here:
[https://github.com/nuxt/nuxt.js/blob/v1.0.0/lib/core/renderer.js#L17](https://github.com/nuxt/nuxt.js/blob/v1.0.0/lib/core/renderer.js#L17)

**Comment by DiederikvandenB** [comment]
Can you provide your sentry module version?

**Comment by DiederikvandenB** [comment]
In case you're not on version 1.0.0 of the sentry module package, please try upgrading. This issue should have been resolved with the release of v1.0.0. Let me know if this does not work for you.

**Comment by steffen1249** [comment]
I'm on version 1.0.0 of the sentry module.
The thing that got fixed when you released version 1.0.0 was that the nuxt hook before was called "this.nuxt.plugin" and in the new release of nuxt it's called "this.nuxt.hook". This is working fine.

The problem I'm describing above is that the errorMiddleware is not on the renderer anymore, which makes it undefined.

**Comment by DiederikvandenB** [comment]
Right, I'll take a look at this after the weekend.

**Comment by DiederikvandenB** [comment]
Well, had a little spare time. I submitted a PR for NuxtJS [here](https://github.com/nuxt/nuxt.js/pull/2703). As soon as that is merged in, the commit I just pushed here should get everything working again. I'll release after the merge.

**Comment by DiederikvandenB** [comment]
Issue has been resolved with the release of v1.0.1. Make sure to update Nuxt too! Thanks again for reporting @steffen1249.
